### ISSUE TITLE
Invite Heiko Henning to join as code owner

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec#1008]
I'd like to invite @GreenRover to join the spec (and related repos: bindings, spec-json-schemas) as a code owner. Heiko has been contributing for a while now and he has contributed one of the coolest (if not the coolest) features of AsyncAPI 3.0.0, i.e., request/reply support.

That said, I haven't checked with Heiko beforehand so he would have to agree first, of course 😄 

@derberg @smoya @dalelane @char0n

**Comment by GreenRover** [comment]
Thanks for this honor. I am happily accepted the nomination.

**Comment by smoya** [comment]
Yes Yes Yes!🙌

**Comment by derberg** [comment]
Sounds good to me 🚀 Through request/reply work I'm sure @GreenRover learned a lot on how things work here and how the process of adding features looks like, and how important it is to accommodate different use cases.

**Comment by char0n** [comment]
Of course yes, we all remember request/reply exceptional work ;)

**Comment by dalelane** [comment]
sorry - yes, happy to support this

**Comment by smoya** [comment]
@GreenRover if you are still into this, do you want to create a PR adding your user to the `CODEOWNERS` file on:

- https://github.com/asyncapi/spec
- https://github.com/asyncapi/spec-json-schemas
- https://github.com/asyncapi/bindings
- https://github.com/asyncapi/parser-js (not sure if you are happy with this one as well 🤔. I don't recall if you ended up working on it)

**Comment by GreenRover** [comment]
The PRs are created:
- https://github.com/asyncapi/spec/pull/1017
- https://github.com/asyncapi/spec-json-schemas/pull/489
- https://github.com/asyncapi/bindings/pull/241

@fmvilas I try to earn me code ownership for parser-js may be later. I guess there are enough open todos.

**Comment by fmvilas** [comment]
Yeah, don't get me wrong, I don't know if you deserve to be a code maintainer of the parser or not. I just wanted to clarify that becoming a code owner of the spec gives you the right to become code owner of bindings and spec-json-schemas but not other stuff. Or at least that's what I remember we discussed 😄

**Comment by smoya** [comment]
I recently announced it [in Slack](https://asyncapi.slack.com/archives/C34F2JV0U/p1707223718550249). @thulieblack will schedule a Tweet for ~tomorrow. (Thanks!)

Closing the issue
