### ISSUE TITLE
Send/Receive again confusion

### ISSUE THREAD

**Issue by skonik** [asyncapi/spec#1011]
Hello everyone. I've read 3.0 spec changes, but it's still confusing to understand send/receive.

Is it correct that now we think from the perspective of service described in asyncapi? (look at the picture below)

![asyncapi_v3](https://github.com/asyncapi/spec/assets/50069473/9eff1370-98a5-4264-a7d0-768995376d55)

It would be very helpful to update documentation with some drawings, because it's still a little bit confusing

**Comment by dalelane** [comment]
> Is it correct that now we think from the perspective of service described in asyncapi?

The intent is now that you specify this from the perspective of **the application being described** by the AsyncAPI document.

Therefore, if your application is sending messages, you use `send`. If your application receives messages, you use `receive`.

**Comment by skonik** [comment]
Perfect. Thanks
