### ISSUE TITLE
Undefined description when using `OneOf`, `AllOf` or `AnyOf`

### ISSUE THREAD

**Issue by jaymorelli96** [asyncapi/spec#1013]
I am not sure if this is the intended behaviour or not, but whenever using the `OneOf`, `AllOf` or `AnyOf` when rendering the document it is represented as `undefined`. 

![image](https://github.com/asyncapi/spec/assets/61237619/4b6d7dbd-0cfd-4d3d-bc86-7060384f323a)

This image is from the official template `WebSocket`

Is there a way to fix this? It is very confusing to read the document when there are complex objects.

**Comment by SebastianKotstein** [comment]
Add a `title` property to the referenced schema. Then, this title will be displayed instead of undefined.
