### ISSUE TITLE
Undefined behaviour of "messageId" for Message Traits and Messages defined in components.

### ISSUE THREAD

**Issue by tomsfernandez** [asyncapi/spec#1014]
HI! According to the specification from version 2.4 and onwards, the `messageId` field:
> The id MUST be unique among all messages described in the API. The messageId value is **case-sensitive**

Now, what happens if I define a messageId in a trait or in a component? I will only be able to re-use that trait or component one time because if I reference it more than once then I would be repeating messageId. Is this the correct interpretation of this feature or should I be thinking it differently ?

How is tooling handling these cases?

**Comment by ScottSusman** [comment]
Same question.

**Comment by derberg** [comment]
Solved with 3.0

Prior, yes, you kinda have a problem that if you will put `messageId` in a message trait or `operationId` in an operation trait and then reuse those in multiple messages/operations in the same document you will get an issue as it basically means you duplicate the ID information - reason is that for traits [JSON Merge Patch](https://datatracker.ietf.org/doc/html/rfc7386) is used
