### ISSUE TITLE
Multiple reply addresses 

### ISSUE THREAD

**Issue by mvuckovic** [asyncapi/spec#1052]
Hello! 

I'm trying to document MQTT Request/Response pattern where a single Request can result in multiple channel/message replies, something similar to [AWS IoT Core Shadow](https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html#get-pub-sub-topic) `/shadow/get`, `/shadow/get/accepted`, `shadow/get/rejected`

It seems V3 currently only supports a single [reply address object](https://www.asyncapi.com/docs/reference/specification/v3.0.0#operationReplyObject). Is there any recommended way I could achieve this with the current spec?

Thanks :)

**Comment by jonaslagoni** [comment]
In the current version you would have to create multiple operations where each results in a single reply 🙂 When the feature was created we never discussed that a single operation should be able to result in multiple addresses on a single operation, either through channel or reply 🤔
