### ISSUE TITLE
[FEATURE REQUEST] RAML-like overlays

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec#107]
**Is your feature request related to a problem? Please describe.**
I want to be able to add and/or override parts of the content of an AsyncAPI document, for instance, being able to provide the same documentation in different languages.

**Can't it be tackled using specification extensions?**
No.

**Describe the solution you'd like**
Don't have a solution yet. Will make a proposal soon.

**Describe alternatives you've considered**
Using specification extensions, but it's overly complicated.

**Comment by MikeRalphson** [comment]
See also https://github.com/OAI/OpenAPI-Specification/issues/1722

**Comment by mattbishop** [comment]
OpenAPI has an overlay spec they are working on here: https://github.com/OAI/OpenAPI-Specification/blob/master/proposals/004_Overlays.md

**Comment by fmvilas** [comment]
Thanks, Matt. @darrelmiller, is it going to finally make it to 3.1.0?

**Comment by fmvilas** [comment]
I think that's already in v3, right? We changed the merging algorithm.
