### ISSUE TITLE
application issue

### ISSUE THREAD

**Issue by Anam-shaikh2003** [asyncapi/spec#1079]
### Describe the bug
There is some application link based issuse that page doesn't working in proper manner.
### To Reproduce
1. Create a document with '...'
2. Try to change to '....'
3. Try to validate the document doing '....'

### Sample document
If applicable, add an AsyncAPI document illustrating the problem.

### Screenshots
![issues page](https://github.com/user-attachments/assets/2e457e46-217c-432b-a48f-4644195a4576)
The page is not working .

**Comment by adityakalburgi** [comment]
Hi @Anam-shaikh2003 i can work on this issue!

**Comment by Anam-shaikh2003** [comment]
yes @adityakalburgi of course you can work this issue. But I even don't konw more about it and also how to fix it. I'll work on this.
