### ISSUE TITLE
[2.0.0 REVIEW] Type-safe references

### ISSUE THREAD

**Issue by vearutop** [asyncapi/spec#261]
# AsyncAPI Review Document

|Project name|Reviewers|Company|Spec version|
|------------|---------|-------|------------|
|Not relevant|Viacheslav Poturaev|Not relevant|v2.0.0|

## Our goals with this project are to:
  1. Not relevant

## We expect to:
  1. Reliably validate AsyncAPI schemas with general purpose JSON Schema validator

### 1. References can point to wrong places
For example `message` is allowed to be a reference or an object, reference can point to any place including wrong one like `#/components/parameters/MyParam`. Current JSON schema can not help to invalidate such case.

#### We think it can be solved by...
We can add a spec requirement that local references of component entities MUST point to appropriate component. On schema level such requirement can be enforced by`pattern` constraint of `$ref` value.

#### Overall, we think this challenge/difficulty is...
  * [x] A "nice to have".
  * [ ] A blocker for us to adopt this version of the spec.
  * [ ] Something that doesn't affect the specification.

## Other thoughts?

I've made similar [proposal](https://github.com/OAI/OpenAPI-Specification/pull/1991) to OpenAPI spec where it can be considered a breaking change. Here in AsyncAPI such problem is less relevant as version `2.0.0` is still pending release.

I can submit a PR is that makes sense.

---
_AsyncAPI Initiative — (website: [asyncapi.org](https://asyncapi.org), twitter: [@AsyncAPISpec](https://twitter.com/AsyncAPISpec))_

**Comment by fmvilas** [comment]
I see what you mean. However, adding a `pattern` restriction to local references is fine for, well, local references but remote/file references are impossible to restrict, so that would be a partial solution.

I think validity should be checked using the structure, always. Basically, because you don't know where the definition can come from.

**Comment by vearutop** [comment]
It is true, the definitive solution would be to validate final structure that was resolved from reference(s), unfortunately there is no way to do it with means of JSON Schema (afaik). 

So such validation can be only implemented in a custom tool explicitly aware of `AsyncAPI` realm, which does not scale.

**Comment by fmvilas** [comment]
> unfortunately there is no way to do it with means of JSON Schema (afaik)

JSON Schema does exactly that. It validates that a given JSON object has the expected structure.

**Comment by vearutop** [comment]
I think you've missed an important detail:

> structure that was resolved from reference(s)

JSON Schema is helpless to set any constraints on the destination of `$ref` like here:
```yaml
    parameters:
      streetlightId:
          $ref: '#/components/parameters/streetlightId'
```

**Comment by fmvilas** [comment]
Oh, you mean validating before dereferencing?

**Comment by vearutop** [comment]
I mean validating **after** dereferencing :)
So that a dereferenced value of `#/components/parameters/streetlightId`:
```yaml
      description: The ID of the streetlight.
      schema:
        type: string
```
is validated against against [parameter schema](https://github.com/asyncapi/asyncapi/blob/2.0.0-rc2/versions/next/schema.json#L504).

That would be a perfect solution for me, unfortunately JSON Schema does not (yet) have a spec for that.

---

At the moment the only way to put some validation pressure on referenced value is an indirect validation through `$ref` string itself.

**Comment by fmvilas** [comment]
I see what you mean now. It's interesting indeed. I'm marking it as "under consideration" so I don't forget to review it when planning the next release (2.0.0 is already closed). Thanks!
