### ISSUE TITLE
[FEATURE REQUEST] New tooling intelliJ autocomplete support

### ISSUE THREAD

**Issue by prdatur** [asyncapi/spec#302]
**Is your feature request related to a problem? Please describe.**
Not related.

**Can't it be tackled using specification extensions?**
No

**Describe the solution you'd like**
As with openAPI, it would helpfull to have a autocomplete plugin for intelliJ IDE.
This will allow us to write documentations and specifications without writing invalid asyncAPI files.
Additional, this will give us a chance to include code generators within the IDE (Would be good if this is another plugin to keep things simple).

**Describe alternatives you've considered**
Think there will be none.

**Additional context**
-

**Comment by fmvilas** [comment]
That's definitely something I'd love to have!

**Comment by fmvilas** [comment]
For those interested, @Pakisan made some great progress with https://www.github.com/asyncapi/jasyncapi. I'm closing this issue.  Feel free to continue the discussion there.
