### ISSUE TITLE
[FEATURE REQUEST] security scope

### ISSUE THREAD

**Issue by cappelaere** [asyncapi/spec#418]
**Is your feature request related to a problem? Please describe.**
Current security scopes are at the full API level.  Given the granularity available, it would be great to have it at the message level.

**Can't it be tackled using specification extensions?**
Since scopes are already defined at securty scheme level, they ought to be used at the message level and used for code generation as well.

**Describe the solution you'd like**
I would like to have the ability to define an array of scopes at the message level that would be necessary for a user to have in order to publish or subscribe.  The array would allow anyone of the scopes to be acceptable,

## Example:
```yaml
smartylighting/streetlights/1/0/action/{streetlightId}/turn/on:
    parameters:
      streetlightId:
        $ref: '#/components/parameters/streetlightId'
    publish:
      operationId: turnOn
      traits:
        - $ref: '#/components/operationTraits/kafka'
      message:
        $ref: '#/components/messages/turnOn'
      security:
        - supportedOauthFlows:
            - streetlights:turnOn
```

**Comment by derberg** [comment]
Hi @cappelaere, could you please format the code sample with markdown so it is easier to read? Thanks

**Comment by cappelaere** [comment]
Updated the example to follow OpenAPI 3.0 to apply security scopes at the message level.

**Comment by Neverbolt** [comment]
I too would very much like this feature to be included in the base specification, since as of now the authorization constructs are not very advanced and being able to specify scopes at an Operation level would allow a much more fine grained control and documentation as well as code generation:

**Comment by derberg** [comment]
@Neverbolt contribution is always welcome, have a look at our contribution guide that explains how to contribute changes to the spec. Most important before PR is to discuss the solution first. Would love to see how you imagine it fixed in the spec.

**Comment by derberg** [comment]
@cappelaere @Neverbolt you should definitely have a look at https://github.com/asyncapi/spec/pull/584

**Comment by derberg** [comment]
@cappelaere @Neverbolt did you have a chance to look at #584 ?

**Comment by derberg** [comment]
I'm closing this one as there are no responses
@cappelaere @Neverbolt please join discussion #584 ? every single voice from the community helps in adding the feature, especially that we have a champion there that drives the topic
