### ISSUE TITLE
Support more than one schema

### ISSUE THREAD

**Issue by cappelaere** [asyncapi/spec#434]
**Is your feature request related to a problem? Please describe.**
Some of our applications may support different encodings for the same API (example: JSON schema, CBOR, Avro...).  Currently, only one schema is supported in the yml file.

**Can't it be tackled using specification extensions?**
We need the capability to define multiple schemas in yml file

**Describe the solution you'd like**
Need to support different "Named" schemas in the yml file
Need to have relative references to selected schema

**Describe alternatives you've considered**
Use different files for different encodings but this makes it more difficult to maintain.

**Comment by fmvilas** [comment]
Hey Pat! Thanks for your patience. Do you have an example of what you're suggesting here? A bit of context would be great too.

**Comment by iridian-ks** [comment]
I can't speak to what the original requestor intended. But I do have what seems to be the same issue. Our scenario is we have a Kafka topic that has multiple schemas and we need documentation for every schema in the topic for our developers to know all of the different messages they'll need to handle.

Right now, it looks like we have this in the spec:

```
...
"subscribe": {
    "message": {
          "payload": {} #<--- schema defined here
     }
}
...
```

I think what we want is something like this:

```
"subscribe": {
    "message": {
        "payloads": [
             {
                   # first schema
             },
             {
                   # second schema
             }
        ]
    }
}
```

**Comment by magicmatatjahu** [comment]
@iridian-ks HI! `payload` field must contain the [Schema Object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#schemaObject). By default it's a AsyncAPI Schema (which is superset of the JSON Schema in the draft-07), so you can use the `oneOf` combined keyword for the `payload` field, like:

```yaml
subscribe:
  message:
    payloads: 
      oneOf:
        - ... first schema
        - ...second schema
        - ...n schema
```

and you don't need, the `payloads`.

Btw. issue is related to define schemas in the different format, so it's not suit for your case, this issue is related - https://github.com/asyncapi/spec/issues/528

**Comment by derberg** [comment]
> Our scenario is we have a Kafka topic that has multiple schemas and we need documentation for every schema in the topic for our developers to know all of the different messages they'll need to handle.

@magicmatatjahu I think that @iridian-ks is more interested in providing multiple messages definitions with schema than multiple schemas for one message. You can use `oneOf` under `message` object

**Comment by fmvilas** [comment]
@cappelaere would you mind clarifying this issue? Do you mean you need to support multiple schema languages as defined in #622?
