### ISSUE TITLE
Proposal for this repo reorganization

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec#494]
This repo currently contains the following things:

1. The specification
2. Some info and issues about the whole project. E.g., README and Public Meetings issues.
3. JSON Schema versions of the spec
4. Some documents about the plans and road map

I feel like it's a mess already and I think it would be great to reorganize things here so here's my proposal:

1. Rename this repo to `welcome` so the new URL would be github.com/asyncapi/welcome. This repo will contain useful information for newcomers, like the README, public meetings issues, road map, plans, etc.
2. Create a new repo for the spec and call it `spec` :) The URL would be github.com/asyncapi/spec. This repo can contain all the versions of the spec so it can be synced with the [npm package](https://www.npmjs.com/package/@asyncapi/specs).

Ideas? Suggestions? I'd love to hear from you, folks!

**Comment by magicmatatjahu** [comment]
Rather that `welcome` we should rename to `community`, this name reflects more the spirit of communication in an organization. `welcome` is good for newcomers. By `community` we have content for newcomers and long-term users related to our meetings and maybe also in future WiG.

**Comment by derberg** [comment]
we should rename this repo to `spec` to preserve github stars.
there is no need for a separate repo like `welcome` or `community` as we anyway need to make all these documents available to the community in a nice way. So what I mean is, we need new section on asyncapi.com and just have all related docs in `website` repo

**Comment by fmvilas** [comment]
I like your proposal @derberg (great point on the stars) but I think it's still good to have another repo for things that don't belong anywhere yet, like this issue: https://github.com/asyncapi/asyncapi/issues/479. On the `community` repo, we can also have Github Discussions enabled for general support.

**Comment by derberg** [comment]
I think this one is done
