### ISSUE TITLE
Clarifications in documentation of `schemaFormat` and `payload`

### ISSUE THREAD

**Issue by nictownsend** [asyncapi/spec#503]
**Describe the bug**
The documentation for `schemaFormat` : https://www.asyncapi.com/docs/specifications/2.0.0#messageObject states:

```
A string containing the name of the schema format used to define the message payload. If omitted, implementations should parse the payload as a Schema object.
```

My understanding following : https://asyncapi.slack.com/archives/C34F2JV0U/p1614177165056400 is that the `schemaFormat` addition of `+json/+yaml` is primarily valuable when using `$ref` for remote files, to state the format of the schema (so that the parser knows how to handle the file once resolved).

When inlining the schema, while I guess for YAML AsyncAPI document you could put a JSON object - you can't for JSON AsyncAPI as it would not be valid.

My proposal/requested solution is additional help in the documentation for inlining. Something like:
```
When inlining the schema, you should omit the `+json/+yaml` as this is only needed to inform an implementation on the format of a schema by remote reference.
```

I also think the `payload` needs clarifying : 
```
Definition of the message payload. It can be of any type but defaults to Schema object.
```

to include:
```
It should match the format provided in schemaFormat.
```

as initially myself and colleagues thought that meant you could inline the value as a string, and `schemaFormat` was just telling the parser to parse that string as the given format.

**Comment by magicmatatjahu** [comment]
I think that this issue should be closed due to fact that related PR is merged. @nictownsend If you think that something should be added, please reopen issue. Thanks again for the contribution! :)
