### ISSUE TITLE
issue with example correlation-id.yml

### ISSUE THREAD

**Issue by 195858** [asyncapi/spec#509]
The file doesn't seem to be valid.
These are the errors I see when loading it into -https://playground.asyncapi.io/

```
[
  "production/security/apiKey doesn't have a corresponding security schema under the components object",
  "production/security/supportedOauthFlows doesn't have a corresponding security schema under the components object",
  "production/security/openIdConnectWellKnown doesn't have a corresponding security schema under the components object"
]
``` 

This is the example I'm referring to - https://github.com/asyncapi/asyncapi/blob/master/examples/2.0.0/correlation-id.yml

**Comment by derberg** [comment]
@195858 yup, it broke when we started validating these. Would you mind opening a PR with the fix?

**Comment by 195858** [comment]
@derberg - I don't have a fix, I only used all the examples I could find to see how they render after making changes to asyncapi-react and this one didn't work.

**Comment by derberg** [comment]
@195858 as far as I see it should be enough to copy over https://github.com/asyncapi/spec/blob/2.0.0/examples/2.0.0/streetlights.yml#L150-L187

**Comment by 195858** [comment]
See PR #515
