### ISSUE TITLE
[RFC] Create Anypoint MQ protocol and bindings

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/spec#514]
In trying to create AsyncAPI documents that assume [Anypoint MQ](https://docs.mulesoft.com/mq/) as the message broker, It became apparent that this is not possible without binding objects for a new `protocol` for that broker.

I request `anypointmq` to be added to the list of protocols in AsyncAPI, and corresponding binding objects to be defined and added to https://github.com/asyncapi/bindings. These binding objects should describe, among other things:

1. how to connect to an AnypointMQ broker instance using the `server` object
2. how to use AnypointMQ queues (FIFO or not) and exchanges as channels
3. how to use AnypointMQ message specifics like user properties, message ID, et.

**Comment by GeraldLoeffler** [comment]
Development of the requested bindings has been started in https://github.com/integrational/asyncapi-bindings and a PR will be sent once sufficiently progressed.

**Comment by GeraldLoeffler** [comment]
will submit a minimal PR shortly

**Comment by GeraldLoeffler** [comment]
This issue is addressed by these 2 PRs:
- against the spec repo: https://github.com/asyncapi/spec/pull/545
- against the bindings repo: https://github.com/asyncapi/bindings/pull/63

**Comment by GeraldLoeffler** [comment]
This PR https://github.com/asyncapi/asyncapi-node/pull/67 covers the addition of the `anypointmq` protocol to the AsyncAPI JSON schema

**Comment by GeraldLoeffler** [comment]
For reference: the AsyncAPI team has rejected the need for `anypointmq` as a protocol because the interaction with the Anypoint MQ broker is based on HTTP (for which a protocol already exists). I think this rejection stems from a basic disagreement about the purpose of a "protocol" in AsyncAPI. See https://github.com/asyncapi/bindings/pull/63#issuecomment-868270505

**Comment by derberg** [comment]
@GeraldLoeffler the PR is not closed without merge, thus it is not rejected 😉 it is in progress

**Comment by derberg** [comment]
@GeraldLoeffler do you continue this one?

**Comment by GeraldLoeffler** [comment]
> @GeraldLoeffler do you continue this one?

as far as i'm aware @derberg this is complete in all its aspects: it just needs merging (into the spec and bindings repos).

**Comment by derberg** [comment]
PR in the binding repo is still not merged, there are some comments form my side

**Comment by GeraldLoeffler** [comment]
> PR in the binding repo is still not merged, there are some comments form my side

oh i see - i thought this had been accepted weeks/months ago. I'll review your comments and incorporate them if possible.

**Comment by GeraldLoeffler** [comment]
> PR in the binding repo is still not merged, there are some comments form my side

done

**Comment by derberg** [comment]
@GeraldLoeffler we are almost there. PR on binding repo is perfect. PR here in `spec` repo needs minor change (left comment) and we are missing PR to change JSON Schema, PR against `2021-09-release` branch in https://github.com/asyncapi/spec-json-schemas. You can have a look on PR from Dale on IBM MQ binding to see how this should be changed so we see in PR only specific changes (you will need to create new JSON Schema file for new 2.2.0 version, this will be first commit, and then in the 2nd commit add new binding please)

**Comment by GeraldLoeffler** [comment]
> @GeraldLoeffler we are almost there. PR on binding repo is perfect. PR here in `spec` repo needs minor change (left comment) and we are missing PR to change JSON Schema, PR against `2021-09-release` branch in https://github.com/asyncapi/spec-json-schemas. You can have a look on PR from Dale on IBM MQ binding to see how this should be changed so we see in PR only specific changes (you will need to create new JSON Schema file for new 2.2.0 version, this will be first commit, and then in the 2nd commit add new binding please)

i think i've now done all that @derberg . See https://github.com/asyncapi/spec-json-schemas/pull/90 for the JSON Schema PR, and also note the strange files that appeared in that PR (https://github.com/asyncapi/spec-json-schemas/pull/90#issuecomment-911820959).

**Comment by GeraldLoeffler** [comment]
> note the strange files that appeared in that PR ([asyncapi/spec-json-schemas#90 (comment)](https://github.com/asyncapi/spec-json-schemas/pull/90#issuecomment-911820959)).

all cleaned-up, all ready: i assume this will go into 2.2.0?

**Comment by dalelane** [comment]
@GeraldLoeffler Is there anything left to do for this issue or do you think it's okay to close?

**Comment by GeraldLoeffler** [comment]
that's been implemented @dalelane and i wasn't aware that there was this issue left open: please close it. Thank you.

**Comment by dalelane** [comment]
@derberg can you close, please? (I don't have the power 😁)
