### ISSUE TITLE
Bindings are specified differently between objects

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#519]
**Describe the bug**
Operation bindings are described as `Map[string, Operation Bindings Object]` where channel bindings are described as `Channel Bindings Object`

I expected both definitions to be described as either `Map[string, <NAME>]` or `<NAME>`

**Comment by derberg** [comment]
@jonaslagoni do you want to open up a PR for this one?

**Comment by jonaslagoni** [comment]
This is no longer relevant.
