### ISSUE TITLE
AsyncAPI open meeting, Tuesday Mar 13 2021 8 AM UTC 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#526]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [8 AM UTC]()**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
2. Got anything to add? 
3. Q&A

**Comment by derberg** [comment]
@jonaslagoni I'm super curious what just happened 😄

**Comment by dalelane** [comment]
@jonaslagoni Do you mean "Apr 13"? :-)

**Comment by magicmatatjahu** [comment]
Duplicated https://github.com/asyncapi/community/issues/20 😄

**Comment by jonaslagoni** [comment]
You guys are way too fast!
