### ISSUE TITLE
Work on 2.1 release

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#536]
Release 2.1 is scheduled for June -> https://github.com/asyncapi/spec/issues/513

Release branches:
https://github.com/asyncapi/spec/tree/2021-06-release
https://github.com/asyncapi/asyncapi-node/tree/2021-06-release
https://github.com/asyncapi/parser-js/tree/2021-06-release

Contribution guide:
https://github.com/asyncapi/spec/blob/master/CONTRIBUTING.md

Things to do for the release:
- https://github.com/asyncapi/website/issues/86 - @aayushmau5
- automation setup. Release candidates artifacts publishing - @derberg
- social media communication - @derberg 
- release notes - @derberg 
- press release - @Barbanio 
- review docs and examples and update if needed
- draft release process basing on this first experience - @derberg 
- review proposals that were already there for some time and people got familiar with proposed solutions, help push what is possible towards `Stage 3: Accepted`

**Comment by fmvilas** [comment]
I created a new milestone to track all the PRs that will be included in the 2.1.0 release: https://github.com/asyncapi/spec/milestone/17.

**Comment by fmvilas** [comment]
We should be setting a deadline date to include changes in the spec for this release. What about May 30?

**Comment by derberg** [comment]
@fmvilas you think we need it? if we have automation in place before the end of May and also I work on a release notes simultaneously and not leave it until the end, we should be able to accept things that come in later, I think. I think better to think about any deadline once we see there are enough features and then we say like "last 2 weeks" or something like that/

Thoughts?

I still dream about pushing https://github.com/asyncapi/spec/issues/377 😅

**Comment by fmvilas** [comment]
Haha! I think it's important we communicate clearly that we're not just randomly choosing what goes in and what doesn't. A deadline might help.

**Comment by derberg** [comment]
The last time people asked I said that whatever reaches `Stage 3: Accepted` gets in. And it is on us to make sure that there is a setup that supports it.

**Comment by derberg** [comment]
cc @dalelane @magicmatatjahu 

I'm tagging you folks as you should keep a closer look at this issue to learn about new additions if you want to add support to other tools you mentioned in the past, like java template or react component

**Comment by derberg** [comment]
draft PR with release notes opened https://github.com/asyncapi/website/pull/260

@fmvilas I know you did an initial review of changes done between 2.0 tag and the latest master. Please provide the list of changes here or just contribute directly to the release notes article

**Comment by dalelane** [comment]
Can we add the IBM MQ protocol bindings that were defined in https://github.com/asyncapi/bindings/pull/52 ?

If that's okay, I've gotten a couple of pull requests ready to start this:
https://github.com/asyncapi/spec/pull/537
https://github.com/asyncapi/asyncapi-node/pull/58

**Comment by derberg** [comment]
@dalelane I think we have to 😅

**Comment by derberg** [comment]
automation of releases ready for review and merge:
- https://github.com/asyncapi/spec/pull/539 (here I put a long description with screen shots explaining how it will work and what will be release tags)
- https://github.com/asyncapi/asyncapi-node/pull/59
- https://github.com/asyncapi/parser-js/pull/301

in short: for june release, every merge to release branch from one of above repos will result in a tag like this `v2.1.0-2021-06-release.1`, of course this example represents tag on spec repo, parser and others have different version names. Most important is this part `-2021-06-release.1` that will be always there and with every new merge bumped `-2021-06-release.2`. For spec we create only GitHub pre-release, and for parser and asyncapi-node we additionally produce npm package prerelease

**Comment by GeraldLoeffler** [comment]
requesting #545 to be included in spec 2.1

**Comment by derberg** [comment]
I updated release notes with stuff that was added long time ago, last year already to the master + new stuff.

https://github.com/asyncapi/website/pull/260

I made some placeholders for topics that potentially could make it as not much review is needed in these cases, at least this is my assumption 😅 
- add IBM MQ to list of protocols in spec from @dalelane
- add AnypointMQ to list of protocols + binding definition from @GeraldLoeffler 
- extend to examples object from @lbroudoux 

I'm out tomorrow and next week, and @fmvilas is back after next week (so the same time I'm back, afaik). We will have 2 weeks until the end of June so 🤞🏼

**Comment by derberg** [comment]
For next release we need to extend bump action https://github.com/derberg/org-projects-dependency-manager/blob/main/lib/index.js#L79 to support "custom" branch against which the PR is created

**Comment by derberg** [comment]
- IBM MQ is merged (Cc @dalelane )
- AnypointMQ is not merged as it is blocked by not yet merged https://github.com/asyncapi/bindings/pull/63. There are some open questions (Cc @GeraldLoeffler )
- New props for message examples PR is approved but there are things that block review on Parser JS (https://github.com/asyncapi/parser-js/pull/307#pullrequestreview-689371511) and open question to JSON Schema for the spec (https://github.com/asyncapi/asyncapi-node/pull/54#discussion_r656119502) (Cc @lbroudoux)

Automation is almost ready. There is just a small rendering issue that we are solving now.

**Comment by derberg** [comment]
Messages examples from @lbroudoux are merged and RC published.

We just need to check if we can quickly fix issues with rendering nav for the spec in the website

**Comment by magicmatatjahu** [comment]
ConverterJS - https://github.com/asyncapi/converter-js/pull/44
React component with HTML template - https://github.com/asyncapi/asyncapi-react/pull/362
Markdown template - https://github.com/asyncapi/markdown-template/pull/129
