### ISSUE TITLE
effect of inheritance / polymorphism on code generators

### ISSUE THREAD

**Issue by patrickp-at-work** [asyncapi/spec#546]
Hello AsyncAPI community,

with issue #286 an example for declaring a `discriminator` has been added to the spec. Following this example, I've created an asyncapi file and tried to generate code using the [java-spring-template](https://github.com/asyncapi/java-spring-template). My expectation had been to find generated classes `Pet`, `Dog` and `Cat` and I further expected the two latter classes to inherit from `Pet`, so the `petType` would be available as a property of them.

However, the code generator template doesn't work that way. It [always uses aggregation](https://github.com/asyncapi/java-spring-template/issues/90#issue-724558317).

[In this comment](https://github.com/asyncapi/java-spring-template/issues/131#issuecomment-843282787) I have explained why I find it hard to deduct the correct "result expectation" from the specification:

---
>  the code is not going to be what you expect, `petType` property will not be available in Cat and Dog classes

Correct, that's what I would have expected; instead, it generates `AllOfPetCat`.
[...]

> I think this default behaviour is correct. As I understand you expect that in case of discriminator usage, it should be supported?

In fact, I rather think that the specification is unclear about that:

> While composition offers model extensibility, it does not imply a hierarchy between the models.

I interpret that as a way of saying "code generators SHOULD NOT express it with inheritance".

> There are are two ways to define the value of a discriminator for an inheriting instance.

That implies "When the discriminator is present, code generators MUST establish inheritance". The spec then differentiates two examples.
* The first one with the naming choice of `ExtendedErrorModel` looks like a perfect fit for composition / aggregation.
* The second one with the `Pet` looks (at least to me) like a perfect fit for inheritance.
My assumption about inheritance is also re-enforced by the section that describes the `discriminator`:

> The discriminator is the schema property name that is used to differentiate between other schema that inherit this schema. [...] When used, the value MUST be the name of this schema or any schema that inherits it.

But the spec doesn't give any hint how _inheritance_ shall be represented, thus leaving room for interpretation (or confusion :) ).

---

Following the guiding principle "_Understandability is just as important as correctness_" I would like to **ask you for your clarification on what is the best fitting interpretation for code generator when translating the pet example to actual code**.

In addition, "Pet" is probably not a perfect example for class inheritance: It depends on the application context whether "Pet" is considered to be in the "nature" of Dog and Cat, or just seen as a "role" that they take (as compared to the schoolbook example of "Truck" and "Car" clearly inheriting from "Vehicle").

**Comment by patrickp-at-work** [comment]
I had been off for a while, but I'd still be very much interested in your expert clarifications on how to interpret the Pet example in generated code.

**Comment by patrickp-at-work** [comment]
Thanks for adding it to the milestone, @fmvilas.
@gibson042, you are the one who added the example in the spec which this issue refers to. Do you like my proposal from the end of the issue description (Truck / Car / Vehicle instead of Dog / Cat / Pet) to achieve more clarity?

**Comment by gibson042** [comment]
> Do you like my proposal from the end of the issue description (Truck / Car / Vehicle instead of Dog / Cat / Pet) to achieve more clarity?

Yes. :+1:

**Comment by jonaslagoni** [comment]
Is there any of you who wants to champion this? 🙂 Or can we consider this issue as needs champion? 🤔
