### ISSUE TITLE
Distinguish between protocol headers and application headers in runtime expressions

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/spec#556]
I'll use JMS as an example, but the same argument applies to Anypoint MQ and potentially other protocols.

A JMS message defines header, properties, and a body: https://javaee.github.io/javaee-spec/javadocs/javax/jms/Message.html .
JMS uses different API calls to access headers and properties.
JMS headers are equivalent to AsyncAPI protocol headers (i.e., a fixed set of well-known headers defined by the protocol (JMS)).
By contrast, JMS properties are equivalent to AsyncAPI application headers (i.e., headers defined by the message sender to suit its needs).

In AsyncAPI, application headers are specified in the [`headers` field of the message object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageObjectHeaders).
By contrast, protocol headers are specified in the message binding object, by convention in the [`headers` field, as is the case for example in the HTTP bindings](https://github.com/asyncapi/bindings/tree/master/http#messageBindingObjectHeaders).

The [`correlationId` field of the AsyncAPI message object](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#messageObjectCorrelationId) uses [runtime expressions](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md#runtimeExpression) to refer to headers. For example `$message.header#/xyz` refers to a header named `xyz`. But runtime expressions do not distinguish between application and protocol headers: both are designated by the `header
` keyword in the runtime expression. This means that the runtime expression `$message.header#/xyz` cannot be translated into the appropriate JMS API calls without "knowing" that `xyz` is either a protocol header (JMS header) or an application header (JMS property).

There are 2 possible solutions:
1. In AsyncAPI runtime expressions distinguish between protocol headers and application headers. For example, use `$message.header.protocol#/xyz` for the former and `$message.header#/xyz` for the latter.
2. Alternatively, define `header` in runtime expressions in message objects to always mean application headers. And introduce runtime expressions to message binding objects (which deal with protocol-specifics) such that `header` there is defined to always mean protocol headers. For example, `$message.header#/xyz` in the message object (for example in the `correlationId` field) means the application header `xyz`. Conversely, `$message.header#/xyz` in the JMS message binding object (for example in a `correlationId` field to be introduced there) means the protocol header (JMS property) `xyz`.

**Comment by fmvilas** [comment]
Yeah, I think it should go inside the bindings object (solution 2). The same protocol header might be different in each protocol. For instance, `Content-Type` for HTTP and `contentType` for MQTT.

**Comment by smoya** [comment]
Hi @GeraldLoeffler! It has been a while since you created this RFC-0. Do you wanna champion it?
