### ISSUE TITLE
Request the constraint on 'Discriminators' be relaxed

### ISSUE THREAD

**Issue by sekharbans-ebay** [asyncapi/spec#585]
Currently for the **_anyOf_** or **_oneOf_** scenarios the discriminators are limited to a property in the schemas being discriminated. Request this be relaxed to provide references outside the schemas. Here is our use case - i.e our payloads associated with each message delivered:

```json
{
  "metadata": {
    "topic": "string",
    "schemaVersion": "string",
    "deprecated": "false"
  },
  "notification": {
    "notificationId": "string",
    "eventDate": "string",
    "publishDate": "string",
    "publishAttemptCount": 0,
    "data": {
      "username": "string",
      "userId": "string",
      "eiasToken": "string",
      "revokeReason": "REVOKED_BY_APP",
      "revocationDate": "string"
    }
  }
}
```
 
It is consistent across topics except for the ‘data’ part of the definition of which varies based on the medatdata.topic field.
What we would like to do is use  ‘one of’  (or anyOf) with a discriminator that co-relates the data definition to the ‘topic’ field in the metadata section.

Understand this may be inherited from OpenAPI specification - but we need this relaxation specifically in context of AsyncAPi please.

**Comment by fmvilas** [comment]
Hey @sekharbans-ebay, I think JSON Schema's `if-then-else` would suffice for your use case: https://json-schema.org/understanding-json-schema/reference/conditionals.html#id8.

PS: I edited your message to format the code and make it more readable. I hope you don't mind.

**Comment by sekharbans-ebay** [comment]
Hi @fmvilas - with discriminators, we would have better visualizer(playground) support. So discriminators would be a first option if permitted.

But would love to give your recommendation a try! Could you point me to an AsyncAPI sample contract that uses something similar (perhaps in a different context)?  
Thanks so much!

**Comment by fmvilas** [comment]
Hey @sekharbans-ebay, sorry for the late response. I actually don't have any examples but since AsyncAPI leverages JSON Schema, here's the documentation about if-then-else: https://json-schema.org/understanding-json-schema/reference/conditionals.html#if-then-else. Hope that helps.

**Comment by derberg** [comment]
@magicmatatjahu in case you were wondering how important it is to support `if-then-else` in the react component 😄

**Comment by magicmatatjahu** [comment]
Maybe I don't understand, but `if-then-else` has been supported for some months 😄

**Comment by derberg** [comment]
@magicmatatjahu whaaaat! amazing!

you need to definitely improve your commit messages so it is clear from the release notes what cool was released 😛

**Comment by magicmatatjahu** [comment]
@derberg You're welcome 😄  Only discriminator isn't supported, because it's complex to render it and we don't have support for it in the parser (I mean, checking possibilities for discriminator). This issue isn't related to component, but here some example:

![image](https://user-images.githubusercontent.com/20404945/133426668-e6d0b862-5e24-49e3-bff9-7a3472131d1f.png)
![image](https://user-images.githubusercontent.com/20404945/133426735-aa660486-6cb0-44a5-a688-9a3d49cf6206.png)

I hope that you have in mind that feature :)

**Comment by derberg** [comment]
@sekharbans-ebay are you still interested with this one?

**Comment by derberg** [comment]
closing as there is no further response from requestor
