### ISSUE TITLE
should binding specs be tied to specific versions of the AsyncAPI spec?

### ISSUE THREAD

**Issue by GeraldLoeffler** [asyncapi/spec#590]
(Opened as requested in https://github.com/asyncapi/bindings/pull/63#discussion_r676806443.)

When implementing the Anypoint MQ binding spec (PR https://github.com/asyncapi/bindings/pull/63) my instinct was to state the version of the AsyncAPI spec (initially `2.0.0`, then `2.1.0`) that this binding spec was written against/for. There is nothing specifically in the binding spec that requires that exact version of the AsyncAPI spec. But it did feel "right" to state clearly that the binding spec was written assuming the features of that version of the AsyncAPI spec.

Question: should binding specs state the version of the AsyncAPI spec they assume?

**Comment by magicmatatjahu** [comment]
I understand problem, but only use case which I see is situation when we will introduce in the next versions of spec drastic breaking changes for appropriate `channels`, `servers` and in other places where you can and want define binding. I don't see any other way.

When we talk about implementation of your idea, we can support in the binding definition next to the `bindingVersion` the `asyncapiVersion` (or `specificationVersion`) field with form to check the satisfied with spec semver, like [here](https://github.com/asyncapi/html-template/blob/master/package.json#L105), so you will end with binding definition:

```yaml
bindingVersion:  ...
asyncapiVersion: ">=2.0.0 <3.0.0",
```

Additionally I think that we should also support this field (if we decide to supporting it) in the [custom extension](https://github.com/asyncapi/extensions-catalog).

**Comment by magicmatatjahu** [comment]
I think it's still relevant. We should discuss that problem also for extensions. cc @GeraldLoeffler @jonaslagoni (you're interesting in bindings/extensions topic so I ping you)

**Comment by GeraldLoeffler** [comment]
i agree it's relevant @magicmatatjahu , but i personally don't have capacity to champion it

**Comment by magicmatatjahu** [comment]
@GeraldLoeffler No problem, I make a triage to check all stale issues :)

**Comment by jonaslagoni** [comment]
Honestly, I think this will automatically be picked up for 3.0, as we will need to figure out how bindings still make sense and how they should be handled.

**Comment by jonaslagoni** [comment]
As this issue was just [bought up in the 3.0 spec meeting](https://github.com/asyncapi/community/issues/270
) when we discussed https://github.com/asyncapi/bindings/issues/113.

And as this issue just become something we have to think about for 3.0, I wanted to tag all of the [binding codeowners](https://github.com/asyncapi/bindings/blob/master/CODEOWNERS) for input. @rcoppen @lbroudoux @dalelane @damaru-inc @CameronRushton @KhudaDad414 @derberg @fmvilas 

What do you folks think about bindings and the spec relation, how should we handle that?

**Comment by jonaslagoni** [comment]
@GeraldLoeffler would you have any interest in championing this?

**Comment by fmvilas** [comment]
I think the binding spec should explicitly state the minimum and maximum version of the core spec it supports. Just [like we do with Generator templates](https://github.com/asyncapi/html-template/blob/master/package.json#L106) but not necessarily in a machine-readable way. I mean, can be just something that's in the Markdown file of the binding spec.

**Comment by derberg** [comment]
as @fmvilas mentioned we need min/max like in generator, and like @magicmatatjahu wrote, we need it as part of schema, so tooling can check that out

**Comment by jonaslagoni** [comment]
Still relevant.
