### ISSUE TITLE
Explain "traits" and their use-cases

### ISSUE THREAD

**Issue by clemensv** [asyncapi/spec#600]
The spec jumps into defining traits without clarifying use-cases for them. I can imagine them being a way to enforce some uniformity across metadata for several messages at once, but the spec doesn't say that.

**Comment by Fannon** [comment]
We currently have an open PR where we discuss and want to more clearly define the trait behavior. Your feedback on this would be very welcome.

See #532

**Comment by fmvilas** [comment]
Closing as it's a duplicate of #532.
