### ISSUE TITLE
Missing primer and/or deeper intro

### ISSUE THREAD

**Issue by clemensv** [asyncapi/spec#601]
The spec is generally rather light on explaining the motivation for the spec itself and for its elements. I don't think pointing to OpenAPI is sufficient. 

OpenAPI has a fairly straightforward job:  Define a set of operations that are immediately realized by a (synchronous) web service implementation and exposed to an application via proxy code.

AsyncAPI, as I see it, has a more complicated job because it defines flows that involve intermediaries which may not be in control of the API implementation owner, and potentially multiple layers of such intermediaries, and that requires quite more elaboration to achieve interoperability.

For instance, let's consider a backend service in a retail scenarios that sits behind a queue and that understands three different messages. The messages originate from a point-of-sale system and are initially queued up in an on-premises system and then replicated into the backend system with some sort of shovel. That is quite common. 

How does the security section in the AsyncAPI map to such a scenario? The backend service API owner is likely neither in control of securing the broker-to-broker integration flow from the on-premises queue to the backend queue, and it's definitely not in control of how the mobile front-end device interacts with the on-premises broker. Does each layer have its own AsyncAPI document that refers to a shared base document?

The security section's discussion around scopes, with the "write:pets" and "read:pets" examples, also seems to imply that there are  application-specific authorization rules being defined here, but how does that work through two layers of middleware?  

I also think that AsyncAPI needs to take a much stronger stance on correlated multi-directional flows; I believe that is the niche where the spec can really fill a gap. There are plenty of specs that define schemas for messages and events abstractly (not the least CloudEvents in CNCF), but there's a real gap in defining multi-directional conversations abstractly: Not just request/reply, but also scatter/gather patterns, saga patterns, etc.  

How does a typical sequence diagram describing a multi-directional conversation between four parties map to an AsyncAPI document?

**Comment by fmvilas** [comment]
I'm not sure I fully understand your point here. Currently, AsyncAPI defines what an application expects on a set of given communication channels. It is application-centered and therefore we don't care about the topology. This way of defining communication has drawbacks but we're working on them primarily at #390 (and related issues at #520). Most probably, a version 3 of AsyncAPI would define what an application **does** as opposed to what an application expects. This way, a 4-layer system can be described using 4 different AsyncAPI files (one per application/middleware).

> How does a typical sequence diagram describing a multi-directional conversation between four parties map to an AsyncAPI document?

Using multiple AsyncAPI files, one per party.

---

That said, and given your experience, would you mind opening a proposal with a clear solution of how to fix the problems you're concerned about? That'd be helpful.

**Comment by derberg** [comment]
so far based on the initial description I think you might think of:

- kinda spec like https://github.com/serverlessworkflow/specification/blob/main/specification.md that btw soon will release 0.7 and support AsyncAPI
- or library like https://github.com/asyncapi/app-relations-discovery that can consume multiple AsyncAPI files and draw an architecture diagram of flows (except it is not able to guess a sequence but just show relations)

**Comment by fmvilas** [comment]
Alright, let me check again with LF and I'll get back to you.

**Comment by smoya** [comment]
Describing workflows through the spec has been lightly mentioned [here](https://github.com/asyncapi/community/discussions/91#discussioncomment-1447823). https://serverlessworkflow.io is there for that reason and you can find an example in the referenced comment.

**Comment by iancooper** [comment]
@smoya This might be different to a workflow via a state machine. IMO it has more in common with flow-based programming or reactive.
