### ISSUE TITLE
Inconsistency between Message.examples and MessageTrait.examples

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#604]
**Message.examples** description

> An array of key/value pairs where keys MUST be either headers and/or payload. Values MUST contain examples that validate against the headers or payload fields, respectively. Example MAY also have the name and summary additional keys to provide respectively a machine-friendly name and a short summary of what the example is about.

**Message.trait** description

> An array with examples of valid message objects.

I propose we unify these description and use `Message.examples` description in `Message.trait` description. 

If agreed I can issue a PR.

**Comment by magicmatatjahu** [comment]
@char0n Good catch! `Message Trait`s `examples` should have this same shape as `Message.examples`.  PR will be more than welcome :)

**Comment by char0n** [comment]
PR issued https://github.com/asyncapi/spec/pull/608

**Comment by char0n** [comment]
PR https://github.com/asyncapi/spec/pull/608 has been accepted and merged and became part of 2.2.0.
