### ISSUE TITLE
Proposal to create new Message Example Object

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#606]
Current situation is that `Message.examples` and `MessageTrait.examples` are using generic type of `[Map[string, any]]`. Then the description of `examples` field provide more structure:

> An array of key/value pairs where keys MUST be either headers and/or payload. Values MUST contain examples that validate against the headers or payload fields, respectively. Example MAY also have the name and summary additional keys to provide respectively a machine-friendly name and a short summary of what the example is about.

IMHO this description warrants a new `Message Example Object` with fixed fields, instead of defining the structure with generic type and description. I propose to introduce new `Message Example Object` with following definition:

#### <a name="messageExampleObject"></a>Message Example Object

`<description placeholder>`

##### Fixed Fields

Field Name | Type | Description
---|:---:|---
<a name="messageExampleObjectHeaders"></a>headers | `Map[string, any]` | `<description placeholder>`
<a name="messageExampleObjectPayload"></a>payload | `any` | `<description placeholder>`
<a name="messageExampleObjectName"></a>name | `string` | A machine-friendly name.
<a name="messageExampleObjectSummary"></a>summary | `string` |  A short summary of what the example is about.

---

`Message.examples` and `MessageTrait.examples` type will subsequently change to `[Message Example Object]`

**Comment by fmvilas** [comment]
Yeah, I think it would be a great idea 👍 

Just a comment on the process side of things. For the proposal to be Stage 1 (RFC 1) it has to be a PR, not an issue: https://github.com/asyncapi/spec/blob/master/CONTRIBUTING.md#stage-1-proposal. It's ok as I don't want to be picky but thought you'd like to know 😊

**Comment by char0n** [comment]
> Just a comment on the process side of things. For the proposal to be Stage 1 (RFC 1) it has to be a PR, not an issue: https://github.com/asyncapi/spec/blob/master/CONTRIBUTING.md#stage-1-proposal. It's ok as I don't want to be picky but thought you'd like to know

You're absolute right ;] I'll read the document and align my efforts with the established processes.

**Comment by char0n** [comment]
Formal proposal has been issued via PR: https://github.com/asyncapi/spec/pull/609

**Comment by char0n** [comment]
We can close this. The proposal has been accepted, [merged](https://github.com/asyncapi/spec/pull/609) and became part of 2.2.0.
