### ISSUE TITLE
Where should the required MQTT topic be stored?

### ISSUE THREAD

**Issue by cdavernas** [asyncapi/spec#632]
I am working on a client used to interact with a remote MQTT message broker described by an AsyncApi document. Though most of the work can be easily done with what the spec already defines, I'm stuck when trying to resolve the MQTT topic a given message should be published to or subscribed from.

I had a good look at MQTT server, channel, operation and message bindings, and none seems to expose a property used to define the topic, making it impossible to dynamically create an AsyncApi client wrapper for MQTT based on a document.

Any clues on how to proceed? Should I just use the channel's key, as it seems to be the case for the [StreetLights MQTT](https://github.com/asyncapi/spec/blob/3470a6386736cf6002846d8eb7535308b79c75e8/examples/streetlights-mqtt.yml) example?

**Comment by jonaslagoni** [comment]
Hey @cdavernas, yes you are right, the channel key is what you use as a topic in MQTT 🙂

**Comment by cdavernas** [comment]
@jonaslagoni Thank you!
