### ISSUE TITLE
Improve readability of spec changes

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#645]
### The problem
In the last two releases, we have simply [linked to a blog post stating the changes](https://github.com/asyncapi/spec/releases), however, with release notes available, I think we should utilize them. I should not have to access a blog to view them, as what if the website is down, blog post got mixed up by some internal problem, and in general, I just think it is a bad user experience. 

### What needs to change
We will need to change the [release process document](https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md) to describe how you can merge the release branch to master with detailed information about the changes and links to PR's.

For the 2.2.0 release, I would have expected the release notes to be:

### Features

* release 2.2.0 spec version

### Release notes
These are the changes that happened in 2.2.0.

Useful links:
Website changelog: https://www.asyncapi.com/release-notes-2.2.0
Blog post: https://www.asyncapi.com/blog/release-notes-2.2.0

#### Features
- Assign channels to servers ([#531](https://github.com/asyncapi/spec/issues/531)) ([8f5ac24](https://github.com/asyncapi/spec/commit/8f5ac24792644a2c0ba6ce834be25f74523976ea))
- Updated all examples to version 2.2.0 ([#629](https://github.com/asyncapi/spec/issues/629)) ([5ea666b](https://github.com/asyncapi/spec/commit/5ea666b9b80f45712411b757ba6b8b37101f337e))
- Add Anypoint MQ protocol to list of supported bindings ([#545](https://github.com/asyncapi/spec/issues/545)) ([88e2b08](https://github.com/asyncapi/spec/commit/88e2b08f2e8c1860266b6795c652fad08c330c67))

#### Fixes
- Unified Message and MessageTrait examples description ([#608](https://github.com/asyncapi/spec/issues/608)) ([6887699](https://github.com/asyncapi/spec/commit/688769971773531a9409077dd368d393cad8a94f))

**Comment by derberg** [comment]
@jonaslagoni why did you add it needs champion? it is not related to RFC process right? you just want to improve the details we put in the Release Notes when releasing the spec, right?

**Comment by jonaslagoni** [comment]
Yes, in my mind that change needs a champion too 😆 We need to adapt the [release process document](https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md), right?

**Comment by derberg** [comment]
well, it needs someone to open up a PR with slight modifications in the instruction. You can also ask @dalelane if he could take it on as I see he liked the idea, and as current release coordinator, I'm sure he will have some improvements to the process for future release coordinators 😄 

I'm removing the label as it is strictly related to RFC process 😉

**Comment by dalelane** [comment]
sounds like a good idea - I can't assign myself to the issue, but happy to pick it up - I'll include it in the updates I make to the release process

**Comment by derberg** [comment]
awesome, we do not assign issues really but I can do it if you want
done

**Comment by derberg** [comment]
afaik it is done already, latest release looks pretty neat and Sergio also update release process doc
