### ISSUE TITLE
Sequence diagram or stateful applications

### ISSUE THREAD

**Issue by stalkerg** [asyncapi/spec#652]
After googling and reading the documentation I didn't find a way to describe a sequence of messages. As I understand the current OpenAPI base on the idea what each message is independent. 
I have stateful protocol and I should describe state-machines and reactions at each time or in each stage. As I understand it should be some addition to the current asyncapi. A sequence diagram basically can solve it but it has no sense to use without asyncapi/openapi. 
It's a question and maybe proposal to cover stateful protocols as well. 

Regards,

**Comment by stalkerg** [comment]
I believe it's related to #618

**Comment by smoya** [comment]
@stalkerg There is an ongoing RFC-0 that includes https://github.com/asyncapi/spec/issues/558 request/reply exchange pattern that can be of your interest.

**Comment by stalkerg** [comment]
@smoya yes, it's like a special case for what I want to see. In request/response we have shared state for two messages (include error messages). In my case, I need a little bit more.

**Comment by jonaslagoni** [comment]
@stalkerg would be really helpful if you showed an example as to what you want to describe and how the spec currently comes short of that.

An example could be to adapt the upcoming [Social Media example](https://github.com/asyncapi/spec/pull/651) as a starting point and introduce something new that is stateful, and how you currently can describe it, and where the spec comes short i.e. what you cannot define 🙂

**Comment by stalkerg** [comment]
@smoya thanks, for the links, looks like it's an existent issue, but unfortunately, everybody tried to provide a limited solution. 
Request/response it's just a group (or pair in basic case) of messages with shared unique fields, like id (without it will be sync API). 

@jonaslagoni yes, I should. After googling, looks like not so many people try to go beyond UML seq diagrams and UML state graphs.  I just want to say, it describes the use case or user story will be 50% of success. I will do it soon.

But basically, I should add the concept of states and sequence. You can imagine chatting with rooms or game lobbies when after game matching you can play only in one lobby. In that case, you have several states like:
* not authorized
* authorized
* in lobby/chat room

Depending on the state you have different API (messages types), also you can't randomly change these states. Also, sometimes you can receive messages in some sequence (logging bootstrap on a server). 
I should, describe it's better but I believe it's should provide a quick introduction.
