### ISSUE TITLE
Should we have freeze period on release process?

### ISSUE THREAD

**Issue by magicmatatjahu** [asyncapi/spec#667]
In the [Which tools wants to stay up to date with the spec release?](https://github.com/asyncapi/spec/issues/662) discussion, I suggested that we should have a "freeze period" in the release process to allow us to update tooling on time. Comment below:

https://github.com/asyncapi/spec/issues/662#issuecomment-987862305

> One of the problems that I also see in updating tools is the situation that occurred in the previous release. On the same day as the tools were updated we also merged changes in spec/json-schemas/parser on the release branch - this caused situations when e.g. people needed to know about the changes but did not have a "pre-release", which could be tested in tools. We needed some kind of freeze period in which we have the spec/json-schemas/parser merged (of course on the pre-release branch) and people can use them in the tools, e.g. 1-2 weeks. We are waiting for the tools update and then we do a full spec and tools release. What do you think?

So it's a question: is a valid in our case to have a freeze period? If yes, how long? For minor changes 1-2 weeks, for major 1-2 months, or ever more? What do you think?

cc @derberg @fmvilas @jonaslagoni @smoya

**Comment by jonaslagoni** [comment]
Because we have such a huge focus on tooling, I think it makes sense. 

I suggest we keep the freeze period consistent as everyone knows exactly what to expect. Because we need to give tooling developers adequate time to adapt, I feel like 1 month is the way to go.

**Comment by derberg** [comment]
How is it going with the freeze period? 😆

**Comment by magicmatatjahu** [comment]
@derberg We just tested it on the example of this issue 🤣 Let others comment, I think that for 3.0.0 we should have some month two of such period.

cc @derberg @fmvilas @jonaslagoni @smoya @dalelane

**Comment by jonaslagoni** [comment]
For 3.0.0 I would suggest we try with a 1-month buffer, meaning if we want to release it in Januar, we stop adding new changes to the spec in December 🙂 That way it's a start, and we can evaluate in retrospect how it went.

Adding it as a suggestion for tomorrow's 3.0.0 meeting: https://github.com/asyncapi/community/issues/453

**Comment by fmvilas** [comment]
I would actually suggest we give it 3 months. It's going to be a huge change 😅

**Comment by jonaslagoni** [comment]
> I would actually suggest we give it 3 months. It's going to be a huge change 😅

Well, yes that is true, but remember parser should already be up to date before the freeze period, and those who worked on the spec that also works on tooling, have their hands free as no further changes are happening from that front. So I actually don't think it's that bad 😄

**Comment by smoya** [comment]
> I would actually suggest we give it 3 months. It's going to be a huge change 😅

+1

**Comment by dalelane** [comment]
For v3, and major versions in general, I agree - a few months is sensible. 
For minor versions, it feels less urgent to me though
