### ISSUE TITLE
Work on 2.3 release

### ISSUE THREAD

**Issue by dalelane** [asyncapi/spec#675]
Release 2.3.0 is scheduled for January 2022

### Detailed info:
* https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md

### Kick-off:
* https://www.youtube.com/watch?v=9lJY5NcLMKY

### Release branches:
* https://github.com/asyncapi/spec/tree/2022-01-release
* https://github.com/asyncapi/spec-json-schemas/tree/2022-01-release
* https://github.com/asyncapi/parser-js/tree/2022-01-release

### Release notes:
* draft PR - https://github.com/asyncapi/website/pull/512

### Progress:
- [x] Create release branches
    - [x] spec - https://github.com/asyncapi/spec/tree/2022-01-release
    - [x] spec-json-schemas -  https://github.com/asyncapi/spec-json-schemas/tree/2022-01-release
    - [x] parser-js - https://github.com/asyncapi/parser-js/tree/2022-01-release
- [x] Update release branches with new versions
    - [x] spec - https://github.com/dalelane/spec/commit/8c521539cd875470ea8e89cf3ab7ffd81be64788
    - [x] spec-json-schemas - https://github.com/dalelane/spec-json-schemas/commit/9cff7798ac42f609927e1cb9e532ff16d360ab99
    - [x] parser-js - https://github.com/dalelane/parser-js/commit/52b4cbe99b4d1247aa1a5e04f766b26fd61d8c0d
- [x] Update release branch name in package.json
    - [x] spec - https://github.com/dalelane/spec/commit/210f89adc74f17aaf09d808b84132f232ff2e412
    - [x] spec-json-schemas - https://github.com/dalelane/spec-json-schemas/commit/8a4b94aaf86240a6ca2aeb7ce3cc515bad283a2d
    - [x] parser-js - https://github.com/dalelane/parser-js/commit/1d9f9ed52718269ffbce4d32bd4635c690371f80
- [x] Create draft release notes - https://github.com/asyncapi/website/pull/512
- [x] Update release branches from forks
    - [x] spec - https://github.com/asyncapi/spec/pull/676
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/139
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/426
- [x] Notify community about release branches - [slack message in `#03_specification`](https://asyncapi.slack.com/archives/C0230UAM6R3/p1641375634291500)
- [x] Check for potential release contributions
- [x] Write release notes for new features and changes
    - [x] Add Solace bindings - https://github.com/asyncapi/website/pull/512/commits/f5a5476b87cb5178145c96d7e7d4b2f48b6a4916
    - [x] Allow servers and channels to be defined as components - https://github.com/asyncapi/website/pull/512/commits/7ccf8667dc9f421b2deb82df00a6d7a64dfa5958
    - [x] Make channels optional - https://github.com/asyncapi/website/pull/512/commits/420ef202e8737f87d0ad2268b75cb317b45cce03
    - [x] Make regular expressions ECMA-262 compliant - https://github.com/asyncapi/website/pull/512/commits/4b3ad228f9ecadd34220ca0042ddf159edb278d7
- [x] Prepare pull requests to merge release branches into master
    - [x] spec - https://github.com/asyncapi/spec/pull/681
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/142 
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/433
- [x] Notify tsc_members about upcoming release
- [x] Merge release branches into master
    - [x] spec - https://github.com/asyncapi/spec/pull/681
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/142 
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/433
- [x] Write release notes for the releases on Github 
- [x] Create releases on Github
    - [x] spec
    - [x] spec-json-schemas
    - [x] parser-js
- [ ] Update RELEASE_PROCESS doc with any changes

**Comment by derberg** [comment]
@dalelane you rock mate. Feel free to also communicate it in the #specification channel in slack.

I see your checklist and I think "omg I love when someone does something I did in the past and with first iteration it is already done better" 😄 

I only need more explanation on `parser-js (default branch)` and other related `(default branch)` items

**Comment by derberg** [comment]
maybe https://github.com/asyncapi/website/pull/512 should include also updates to docs and other stuff on the website?
we forgot about it in 2.2 entirely, would make sense to do it this way for 2.3 and make it explicit in release process. What do you think?

**Comment by derberg** [comment]
@dalelane yo, after merging your initial release PRs to release branches, I opened these PRs:
- https://github.com/asyncapi/spec/pull/681
- https://github.com/asyncapi/spec-json-schemas/pull/142
- https://github.com/asyncapi/parser-js/pull/433

there is explanation why we need them, when you will push some improvements to release instruction, please specify info about these "release" PRs, that they should not be created at the end, but since the very beginning, and monitored regularly in case some merge conflicts are discovered (can happent that some editorial change in master can cause conflict in the release branch)

**Comment by smoya** [comment]
FYI @dalelane @derberg we need also this fix to be merged asap https://github.com/asyncapi/spec/pull/695

**Comment by dalelane** [comment]
Four open pull requests are currently targetting release branches:

- spec (_[query to see open pull requests](https://github.com/asyncapi/spec/pulls?q=is%3Apr+is%3Aopen+base%3A2022-01-release+-label%3Ado-not-merge)_)
    - https://github.com/asyncapi/spec/pull/696 
- spec-json-schemas (_[query to see open pull requests](https://github.com/asyncapi/spec-json-schemas/pulls?q=is%3Apr+is%3Aopen+base%3A2022-01-release+-label%3Ado-not-merge)_)
    - https://github.com/asyncapi/spec-json-schemas/pull/148
    - https://github.com/asyncapi/spec-json-schemas/pull/155
- parser-js (_[query to see open pull requests](https://github.com/asyncapi/parser-js/pulls?q=is%3Apr+is%3Aopen+base%3A2022-01-release+-label%3Ado-not-merge)_)
    - https://github.com/asyncapi/parser-js/pull/445

**Comment by derberg** [comment]
- #696 is almost there, just final description tuning in progress
- regarding security (pr from spec, json schema and parser), the discussion is still open, and we just have a week to go, not enough time to get it in for 2.3
- https://github.com/asyncapi/spec-json-schemas/pull/155 already merged

**Comment by dalelane** [comment]
just https://github.com/asyncapi/spec/pull/696 left to wait for now

**Comment by derberg** [comment]
[live stream](https://github.com/asyncapi/spec/pull/696) is now merged. We are ready to go next Monday. @dalelane you wanna post an update in slack or busy with the workshop? I can do it for ya if you want, not a problem

**Comment by dalelane** [comment]
@derberg yeah please - if you could, that'd be a big help

**Comment by derberg** [comment]
spec and json schema released, parser almost there


notes for release improvements:
- parties involved should get a kind of invite upfront, with some 4h window when when have to be responsive on a release, to approve, fix and do other things to make release smooth. This should be a role of release coordinator
- we need to automate the process of new release setup, like release branches creation and other configuration. A GitHub Action workflow that `spec` maintainers can trigger with one click and it just sets up stuff. Should be super simple with GitHub CLI

**Comment by derberg** [comment]
parser 1.14 with support of latest spec and it's json schema is out

**Comment by derberg** [comment]
https://www.asyncapi.com/blog/release-notes-2.3.0

**Comment by jonaslagoni** [comment]
I guess we can close this one down as it is complete ✅ 🎉

**Comment by derberg** [comment]
I would prefer we first summarize what action points need to be taken from this release to improve for 2.4.0

**Comment by smoya** [comment]
I think we can close this one now that https://github.com/asyncapi/spec/pull/722 got merged. WDYT @dalelane ?

**Comment by dalelane** [comment]
oh yeh, good point - I'd forgotten about this! :-)
