### ISSUE TITLE
Remove `$ref` field from `Channel Item Object` in next breaking change version (3.0.0)

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#699]
This is continuation of https://github.com/asyncapi/spec/issues/607. Changes for AsyncAPI 2.3 has already been issued.

**AsyncAPI 2.3**

The aim here is to limit complexity and bring more flexibility.

- [x]  Deprecate the use of `$ref` fixed field in `Channel Item Object`
- [x]  Introduce new fixed field called `channels` in `Components Object` with type of Map[`string`, `Channel Item Object`]

**AsyncAPI 3.0.0**

The aim here is to have single referencing mechanism within AsyncAPI 3.x spec (reducing complexity) - `Reference Object` 

- [x] Remove `$ref` from `Channel Item Object` fixed fields
- [x] Change `Channels Object` patterned field type to `Reference Object | Channel Item Object`
- [x] `Components Object`.`channels` field type will change to Map[`string`, `Channel Item Object` \| `Reference Object`]

**Comment by char0n** [comment]
[PR](https://github.com/asyncapi/spec/pull/777) has been issued for [next-major-spec](https://github.com/asyncapi/spec/tree/next-major-spec) branch.

**Comment by jonaslagoni** [comment]
As I can see we can close this issue as it's completed both for version 2 and 3.

cc @char0n @fmvilas @derberg @dalelane

**Comment by char0n** [comment]
@jonaslagoni sure, fine with me.

**Comment by derberg** [comment]
I don't think we should close as long as 3.0 is not yet merged and released.
We should rather make sure it is linked in description of https://github.com/asyncapi/spec/pull/759 with info that it will be solved after the merge

**Comment by char0n** [comment]
Be patient @github-actions ;]

**Comment by char0n** [comment]
Reopening due to https://github.com/asyncapi/spec/issues/699#issuecomment-1273650238
