### ISSUE TITLE
Unable to reuse `Server Objects` defined in `Components.servers` field

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#705]
Hello everybody,

While implementing 2.3 support into tooling I've noticed couple of inconsistencies/errors in the specification.
As AsyncAPI 2.3.0 introduced new `Components.servers` field, there is no way how `Server Objects` defined in this map can be used later in the definition.

### Usage in `Servers Object`

I assume first intended usecase was to reference `Server Object` defined in `Components.servers` field in `Servers Object`. This intention is clear from the release article:

![image](https://user-images.githubusercontent.com/193286/152542621-9673fc78-e6ca-4078-8a79-736fdb672ae2.png)

What the article is showing is not possible according to the spec as the `Servers Object` pattern field only allows `Server Object` and not `Server Object | Reference Object`.

### Usage in `Channel Item Object`.`servers` field

With this I'm not 100% sure of the intended usage. The specification says following:

![image](https://user-images.githubusercontent.com/193286/152543308-738af474-25da-48ff-aad3-a4ddab295cda.png)

This limits using referencing `Server Object` to ones defined `Servers Object` (by name). Should we allow referencing the `Server Object` even from `Components.servers` field as well? 

I'll provide a PR in a couple of minutes.

**Comment by jonaslagoni** [comment]
Good catch! 

>This limits using referencing Server Object to ones defined Servers Object (by name). Should we allow referencing the Server Object even from Components.servers field as well?

That would be a new feature, as regardless of what you define in your components sections, servers are not "active" until referenced under `servers`. They are nothing but reusable chunks. So `string` still makes sense to use for `Channel Item Object.servers`. 🙂

**Comment by char0n** [comment]
> That would be a new feature, as regardless of what you define in your components sections, servers are not "active" until referenced under `servers`. They are nothing but reusable chunks. So `string` still makes sense to use for `Channel Item Object.servers`. slightly_smiling_face

Right, I assumed it was like you explained but I'd rather asked ;] Having said that, maybe it warrants clarification in the spec? But maybe not...not sure.

**Comment by jonaslagoni** [comment]
> Right, I assumed it was like you explained but I'd rather asked ;] Having said that, maybe it warrants clarification in the spec? But maybe not...not sure.

Could definitely be now that you can define servers in multiple places 🤔 Maybe another issue for further discussing that?

**Comment by char0n** [comment]
Yeah I think it's worth discussing further. If agreed, I'll extract part of this issue regarding servers to a new one.

**Comment by smoya** [comment]
This issue can be now closed as it got merged and released. @char0n

**Comment by char0n** [comment]
@smoya thanks, closing.
