### ISSUE TITLE
Make Server Variables Object available as reusable objects under the Component object

### ISSUE THREAD

**Issue by danielkocot** [asyncapi/spec#707]
Hello everybody,

it is just an idea that came to my mind when I started to write a new post about AsyncAPI in reference to the releases 2.2.0 and 2.3.0. In my example I'm using two servers description for staging and production. Both of them have the same variable in reference to the port of the server.
So I thought it would be good to make Server Variables Objects available as reusable objects under the Component Object.

But let's discuss about it.

Best,
Daniel

**Comment by danielkocot** [comment]
Yeah, @magicmatatjahu. You're right! Thanks for spotting me to the issue you created.

**Comment by magicmatatjahu** [comment]
> Maybe we can work together on a pull request get the ideas we have in a more clear direction. What do you think?

We can, no problem :) Of course we can also go with direction that first we will add possibility to declare that Server Variable in the `components` section (in the `2.4.0` version of spec) and in the `3.0.0` we will introduce unified Spec Object for both Parameter and Server Variable :) Merge of Server Variable and Parameter will introduce braking change, so we need wait for that for `3.0.0`.

For me, we can go with that new field in the `components` section and in next major version simplify it. cc @derberg @fmvilas @jonaslagoni @smoya

**Comment by fmvilas** [comment]
Yup, always in favor of more and better reusability 👍

**Comment by danielkocot** [comment]
#717

**Comment by danielkocot** [comment]
Related PR #717

**Comment by smoya** [comment]
All PRs have been aproved. Would you mind @derberg @fmvilas or @dalelane mark this as RFC Stage 3 (Accepted) and merge (at least the spec one)?

- https://github.com/asyncapi/spec/pull/717
- https://github.com/asyncapi/spec-json-schemas/pull/174
-  https://github.com/asyncapi/parser-js/pull/476

**Comment by derberg** [comment]
yup, all seems to be there, there is only a merge conflict in one of the PRs

**Comment by smoya** [comment]
This issue can be now closed as it got merged and released. @danielkocot
