### ISSUE TITLE
Improper Apache 2.0 license application

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#711]
Hello everybody,

I've noticed that the Apache 2.0 license is applied to this repository in probably improper way. The license text has been changed in license appendix to provide an explicit copyright notice. This is IMHO an improper application of the license, and by doing this the license looses the `Reusable without rewording` attribute.

![image](https://user-images.githubusercontent.com/193286/152786074-414cdc90-4049-4de7-8fee-87ab10a3eabc.png)

Apache 2.0 license appendix is design to be copied to individual files and only in this case the copyright notice should be changed. But this repo is not using appendix so the best option here would be to create a `NOTICE` file containing explicit copyright notice. The license itself recommends this in **4. d)**. The NOTICE file can contain following:

```
AsyncAPI Specification
Copyright The Linux Foundation
```

I've written more extensive elaboration on this topic here: https://vladimirgorej.com/blog/how-to-apply-apache2-license-to-your-open-source-software-project/

**Comment by char0n** [comment]
https://github.com/asyncapi/spec/pull/783 has been merged directly to master. Closing.

**Comment by smoya** [comment]
@char0n I guess this change should be propagated to each individual repository that applies wrongly the Apache 2.0 license. Right?

cc @derberg @fmvilas

**Comment by char0n** [comment]
@smoya yes, ideally. I can handle it after the release effort is over.

**Comment by smoya** [comment]
> @smoya yes, ideally. I can handle it after the release effort is over.

I think we could use the file replicator action from https://github.com/asyncapi/.github/blob/master/.github/workflows/global-replicator.yml#L3-L9

**Comment by derberg** [comment]
@smoya good catch, definitely we should do it through global workflow so it is synchronized everywhere in the same form
