### ISSUE TITLE
Is there a way to document the guaranteed compatibility mode for produced messages? 

### ISSUE THREAD

**Issue by thake** [asyncapi/spec#727]
We plan to use AsyncAPI as our way to document asynchronous APIs. I was wondering if there is a standardized way of communicating the guaranteed compatibility mode of produced messages. For example, confluent schema registry knows the following [compatibility modes](https://docs.confluent.io/platform/current/schema-registry/avro.html): 
 - BACKWARD
 - BACKWARD_TRANSITIVE
 - FORWARD
 - FORWARD_TRANSITIVE
 - FULL
 - FULL_TRANSITIVE
 - NONE

I would like to make the compatibility mode part of the contract specified by the AsyncAPI spec, but couldn't find any standardized way. Clients which are programmed against the AsyncAPI spec can rely on the compatibility mode. A new version will only be introduced if the compatibility according to the compatibility mode is no longer given.

Is there support for this without specification extensions? If not, do you think this would be a good addition to the spec?

**Comment by dalelane** [comment]
That's an interesting idea. For a historical description of changes-until-now, you could just put them all in the AsyncAPI doc wrapped in a one-of so I suspect there wouldn't be any need to additionally describe the compatibility. 

But I can see this being super useful for a more forward-looking "contractual" commitments (e.g. by specifying the compatibility mode in the AsyncAPI doc, an author can make an ongoing commitment that future versions of the doc/schema will have a certain level of compatibility) 

I haven't seen this done in AsyncAPI docs before, but I think it's worth exploring. 

I suspect this will be more useful for Kafka than some other protocols - or at least protocols that support retaining old/previous events. And certainly that would make it easier to adopt the Apache Avro approach to describing compatibility more or less as-is. But I don't think it'd hurt to try doing it in a protocol-agnostic way, as there's nothing stopping other protocols using Avro or making commitments about future changes, even if it's more common in Kafka.

**Comment by thake** [comment]
Thanks for the feedback, @dalelane!

> That's an interesting idea. For a historical description of changes-until-now, you could just put them all in the AsyncAPI doc wrapped in a one-of so I suspect there wouldn't be any need to additionally describe the compatibility.

I'm not so sure if one-of can be used to describe backward compatible historical changes. As the changes are backward compatible, meaning a newer schema can be used to read messages written with an older schema, one central requirement of one-of is not met: "a message MUST be valid only against one of the message objects". Thus, even documenting that a produced event message is backward compatible might be useful. 

I agree with you regarding documenting incompatible changes: One-of is the way to go for documenting historic versions.

> I haven't seen this done in AsyncAPI docs before, but I think it's worth exploring.

I haven't seen it in AsyncAPI docs either. But I've seen the usage of "compatibility mode" in other event specifications. Zalando makes specifying the compatibility mode mandatory: https://opensource.zalando.com/restful-api-guidelines/#245.

> I suspect this will be more useful for Kafka than some other protocols - or at least protocols that support retaining old/previous events. And certainly that would make it easier to adopt the Apache Avro approach to describing compatibility more or less as-is. But I don't think it'd hurt to try doing it in a protocol-agnostic way, as there's nothing stopping other protocols using Avro or making commitments about future changes, even if it's more common in Kafka.

I totally agree that the compatibility mode should be made protocol-agnostic. 

Besides clearly communicating expectations to consumers, I can think of the following usages of a compatibility mode in the AsyncAPI spec:
- tooling can be provided to check if changes to the message respect the compatibility mode by comparing it to previous message schemas. 
- schema registries having the concept of compatibility can be configured with one single source of truth: AsyncAPI specs.

**Comment by jonaslagoni** [comment]
Somewhat related to https://github.com/asyncapi/spec/issues/697

**Comment by scott-chamberlin-js** [comment]
We're currently looking at a way to enforce similar, so that clients can infer things like who has to upgrade first. Further, this allows us to master schemas that are registered to the schema registry from the AsyncAPI spec. At present the [kafka message binding](https://github.com/asyncapi/bindings/tree/master/kafka#message-binding-object) seems like the best place for the extension, as it already has schema registry specific info.

Here's an example:
```yaml
bindings:
  kafka:
    schemaIdLocation: 'payload'
    schemaIdPayloadEncoding: 'confluent'
    schemaLookupStrategy: 'TopicNameStrategy'
    x-compatibility: 'FORWARD'
```

Wondering if this makes sense to be a part of spec in the kafka message binding? I understand it may be more generic than just kafka, but at present the kafka binding already has good ties to schema registries.
