### ISSUE TITLE
Example Request: AMQP

### ISSUE THREAD

**Issue by lindhe** [asyncapi/spec#738]
#### Reason/Context

On [LKAB](https://www.lkab.com/), we work a lot with AsyncAPI definitions for RabbitMQ (AMQP) applications. It would be lovely to have an AMQP example to start from, since many terms (queue, exchange, topic, etc.) are described by AsyncAPI in slightly non-obvious ways sometimes. I think it can be inspired by the MQTT example, since they are fairly similar protocols...

**Comment by lindhe** [comment]
No please :(

**Comment by lindhe** [comment]
:(

**Comment by magicmatatjahu** [comment]
@lindhe Do you wanna create such an example? Contributions are more than welcome :)

**Comment by AceTheCreator** [comment]
No, please... Currently working on one that can stand as an example
