### ISSUE TITLE
Tool proposal for spec validation in Python / Pydantic

### ISSUE THREAD

**Issue by albertnadal** [asyncapi/spec#747]
### New tool proposal

Hi team, I want to propose a new AsyncAPI schema validation tool for the community/tooling section. I recently published a Python package to let the developers load and validate their AsyncAPI specs using Pydantic classes. I thought this might be useful to the community. Information about the tool is listed below.

**asyncapi-schema-pydantic**
This is an AsyncAPI specification schema implemented using Pydantic classes. It allows you to easily parse and validate your spec.
[https://github.com/albertnadal/asyncapi-schema-pydantic](https://github.com/albertnadal/asyncapi-schema-pydantic)

**Comment by derberg** [comment]
@albertnadal feel free to add it to https://github.com/asyncapi/website/blob/master/pages/docs/community/tooling.md through a PR

and I confirm what @smoya wrote 😄
