### ISSUE TITLE
New diff tool proposal

### ISSUE THREAD

**Issue by udamir** [asyncapi/spec#754]
Hi team, 
I want to propose a new diff tool for the community/tooling section.
I recently published [api-smart-diff](https://www.npmjs.com/package/api-smart-diff) (npm package) which provides utils to compute diff between two API specifications, including AsyncAPI specs. I hope it can be useful to the community.

Demo page: https://udamir.github.io/api-smart-diff
Sources and documentation: https://github.com/udamir/api-smart-diff

**Comment by udamir** [comment]
I also want to propose [api-diff-viewer](https://www.npmjs.com/package/api-diff-viewer) -  React component to view the difference between two JsonSchema or API specifications, including AsyncAPI specs.

Storybook: https://api-diff-viewer.vercel.app
Sources and documentation: https://github.com/udamir/api-diff-viewer

**Comment by derberg** [comment]
Hey @udamir what do you mean by `I want to propose` ?

do you mean put it on the website, on list of tools? or host it under `asyncapi` organization and develop it further here with the community?

**Comment by udamir** [comment]
Hi, put it in the website only. My library is generic and the classification rules are not limited by the AsyncAPI specification.

**Comment by derberg** [comment]
@udamir then go ahead, feel free to [add it to the list](https://github.com/asyncapi/website/blob/master/pages/docs/community/tooling.md) through a PR.

You can also have a look at https://github.com/asyncapi/website/issues/383 to see and comment on our plans to improve tools listing.

**Comment by udamir** [comment]
@derberg 
I also can propose to put [wsapix](https://github.com/udamir/wsapix) in to community/tooling section on AsyncApi website. Wsapix is Nodejs framework for WS API with runtime AsyncAPI generation.

**Comment by derberg** [comment]
@udamir makes sense to me

**Comment by magicmatatjahu** [comment]
@udamir You can create PR for new tool, but please make it in separate PR, ok? :)
