### ISSUE TITLE
Kafka bindings - header - object type in header's json schema

### ISSUE THREAD

**Issue by oogetyboogety** [asyncapi/spec#762]
I would like some clarification on Kafka message bindings with headers. What's the meaning of `- property: type: object` inside a header schema? What would the code bindings do if I did something like this? Is it defined as per spec as a key with the JSON path for the attribute defined in the JSON schema of the header, or is it an actual UTF-8 encoded string of a json object inside that particular value for the Kafka ProducerRecord/ConsumerRecord metadata header's key?

- KafkaMessage: ConsumerRecord
  - Custom Metadata Headers: Headers implements Collection<Header implements Tuple<String, Byte>>
     1. "property.attribute": String, value: Byte or 
     2. "property": String, "{\\"attribute\\": \\"value\\"}": UTF-8ByteString
  - Key: byte
  - Value: byte

**Comment by derberg** [comment]
@oogetyboogety hey, can you link to or quote which part of the spec you actually have in mind?

**Comment by oogetyboogety** [comment]
> Assuming that the code generator already has a [`ProducerRecord`](https://kafka.apache.org/28/javadoc/org/apache/kafka/clients/producer/ProducerRecord.html) called `producerRecord`, would this be a reasonable expectation?
Yes. This is what I was originally thinking when using the spec in this way for my project.
