### ISSUE TITLE
Single source of truth

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#780]
Sometimes there are situations when it is not clear if the source of truth should be the JSON Schema or the markdown specification. To remedy this situation, we can explicitly state following in main README file:

```
The human-readable markdown file is the source of truth for the specification.
```

Whenever there is a conflict, the specification itself is the source of truth before anything else.

**Comment by char0n** [comment]
> I would then like to suggest we do it on the spec document

I guess that's automatically implied that specification itself is the single source of truth. Would be quite uncommon to have this explicitly defined in the specification itself. IMHO having it in README suffice, but don't mind having it in specification itself as well, although as I mentioned it's uncommon.

**Comment by char0n** [comment]
> I believe most users (including potential ones) won't read the README file, but rather navigate through the AsyncAPI website.

Just an idea: how about mentioning it in README and the website? I understand that the website is generated from the markdown document, so we just add the sentence to the website templates as well.

**Comment by smoya** [comment]
> Just an idea: how about mentioning it in README and the website?

Sure, this is what I meant by:

> additionally in the README, I don't mind

**Comment by fmvilas** [comment]
I think this has been done already. Let me know otherwise, @char0n.

**Comment by char0n** [comment]
I confirm, it's been merged into master as editorial change -  https://github.com/asyncapi/spec/commit/02393d166a5c70481bd2f7f7f23d69c4f24b83b1
