### ISSUE TITLE
Proper STOMP Protocol Bindings

### ISSUE THREAD

**Issue by Crain-32** [asyncapi/spec#787]
Please note, this Issue can be seen as an Extension of [Issue 457](https://github.com/asyncapi/spec/issues/457), however due to the age of the original Issue and difference in my approach, I've created this as a separate Issue.

### Why Begin Including STOMP? ###
STOMP as a WebSocket protocol is slowly increasing in use and availability. The following are only a few examples of Enterprise-Ready Open Source Software that support STOMP as a Messaging Protocol
- [RabbitMQ](https://www.rabbitmq.com/protocols.html#stomp) | Message Broker
- [Springboot](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#websocket-stomp) | Wraps Message Brokers
- [ActiveMQ](https://activemq.apache.org/stomp) | Apache Message Broker

Beyond that, STOMP as a protocol is incredibly friendly to new developers, given its ability for messages to be easily printed and created. Finally, the last major change, STOMP 1.2, [was a decade ago](https://stomp.github.io/stomp-specification-1.2.html). Meaning that the protocol as a whole has stabilized in definition.

*Note: STOMP's Messages will also be referred to as "Frames" for the rest of the Issue, to align with STOMP's Protocol.*

#### Bindings ####
STOMP's Server/Channel/Operation/Message bindings need to be properly defined and created. As the Protocol splits Frames into 3 categories, the following are a potential mapping to AsyncAPI's Binding Categories. I'll be using [Spec 2.4.0](https://www.asyncapi.com/docs/specifications/v2.4.0) as the frame of reference for AsyncAPI, and [STOMP 1.2](https://stomp.github.io/stomp-specification-1.2.html) for STOMP Protocol Information. 

- *Server*
  - `MESSAGE` | Server Producer Output.
  - `RECEIPT` | Acknowledgement Frame for Multi-Frame Client Stream
  - `ERROR` | Frame with Error Details, connection is severed after being sent.
  - `CONNECTED` | Required Response to a `CONNECT` Frame.

- *Channel*
  - `SEND` | Client Frame to send information to a Consumer. (Could also be a *Message* Binding)
  - `BEGIN` | Client Frame to link an Identifier to a Multi-Frame Message.
  - `COMMIT` | Client Frame to state the end of a Multi-Frame Message.
  - `ABORT` | Client Frame to cancel a Multi-Frame Message.

- *Operation*
  - `SUBSCRIBE` | Client Frame to connect to a Specific Channel.
  - `UNSUBSCRIBE` | Client Frame to disconnect to a Specific Channel.
  - `DISCONNECT` | Client Frame to disconnect from the Server
  - `CONNECT` | Client Frame to Connect to the Server
  - `STOMP` | Same as `CONNECT`

- *Message*
  - `ACK` |  Client Frame to Acknowledge a Server's `MESSAGE` Frame.
  - `NACK` | Client Frame to state it did not consume the Server's `MESSAGE` Frame.

#### Frame Mapping ####
Using the following example Frame for reference.
```bash
COMMAND
header1:value1
header2:value2
header3:value3

Frame Body
^@ # We'll call this the Null Octet to terminate the Frame.
```
The `COMMAND` line is a `enum` mapped `string`. 
Every header is a `key:value` pair in `string:string` format. All the different `COMMAND`s require certain headers. There are also optional Headers, and any custom Headers are carried into the Message as well.
The Frame Body is the Message Payload, and is assumed to be binary unless a `content-type:MIME` Optional Header is set. Not all frames have a Payload.

With the above stated, we can have an Example Server's API declared as the following. (Assume anything not shown)
```json
{
  "components": {
    "schemas" : {
      "BasicPayload": {
        "type": "object",
        "properties": {
          "foo": {
            "type":"string"
          },
          "bar": {
            "type":"string"
          }
        }
      },
      "MessageHeaders": {
        "type": "object",
        "required": [
          "destination",
          "message-id",
          "subscription"
        ]
        "properties": {
          "destination": {
            "type": "string",
            "format": "uri-reference"
          },
          "message-id": {
            "type": "string"
          },
          "subscription" : {
            "type": "string"
          }
        }
      },
      "command":  {
        "type": "string",
        "enum": ["SUBSCRIBE", "CONNECT", "SEND", "ETC"]
      },
      "MessageFrame": {
        "type": "object",
        "required": ["command", "MessageHeaders"],
        "properties": {
          "command": {
            "$ref": "#/components/schema/command",
            "default": "SEND"
          }
          "MessageHeaders": {
            "$ref" : "#/components/schemas/MessageHeaders"
          },
          "Payload": {
            "$ref" : "#/components/schemas/BasicPayload"
          }
        }
      }
    }
  },
  "channels": {
    "/stomp/{example}" : {
      "parameters": {
        "example": {
          "description": "To show different Channels",
          "schema": {
            "type": "string"
          }
        }
      },
      "subscribe": {
        "operationId": "applicationProducer",
        "message": {
          "$ref": "#/components/schema/MessageFrame"
        }
      },
      "publish": {
        "operationId": "examplePro",
        "message": {
          "$ref": "#/components/schema/SendFrame"
        }
      }
    }
  }
}
```
The above would state we have a Server with a Channel `/stomp/{variable}`. It is sending out our `MessageFrame` defined in the Schema, and consumes a `SendFrame` we'll assume has be defined. I'm not 100% sure on how the Bindings would be integrated, or how to handle multiple input frames. This is because you can send `SUBSCRIBE` and `SEND` to the same channel.

To wrap it up, I'd state the main design blockers would be how to handle the STOMP bindings within the Spec. I believe once that question has a solid answer to it, writing the new bindings would (hopefully) be an easy process.

**Comment by derberg** [comment]
Hey @Crain-32. Thanks a lot for great quality issue 🙇🏼 

I understand you want to basically contribute to https://github.com/asyncapi/bindings/tree/master/stomp

Do you have an example AsyncAPI file with your proposed bindings applied?

**Comment by Crain-32** [comment]
Hey @derberg, sorry for taking a while to response, I've been out of town. (And thank you for calling the issue quality, I really wanted to make it count, since I know STOMP has been brought up before.)

I do not have an example AsyncAPI file, since I wasn't completely positive on how we wanted to integrate it. The difference between `Server`/`Channel`/`Operator`/`Message` Bindings are not clearly defined in that repository, so making an example file is difficult for that reason as well.

The closest I have to an example file is the snippet of what I'd imagine would be in one at the end of the Issue.

**Comment by Crain-32** [comment]
@derberg Hey, just wanted to follow up on the above. 

As mentioned, I don't have a direct example file, however if you want me to make one, feel free to ask. I'd like to work on this again in the coming week, as we're still working on supporting STOMP in springwolf, but we can't complete that till the official spec is created.

**Comment by derberg** [comment]
@Crain-32 yeah the example with how you see binding in use would help a lot. 

I'm super interested in this subject because when I was working on [this article](https://www.asyncapi.com/blog/websocket-part2) using [Kraken API](https://docs.kraken.com/websockets/) it was a first time when I saw folks using `Websocket` only as a connection and then some specific protocol for messages exchange. I'm still trying to figure out what protocol they use, if STOMP or something custom 😅 especially that I noticed other crypto fintech do the same in their APIs (like [Gemini](https://docs.gemini.com/websocket-api/#market-data-version-2) that in their v2 did "classic" `Websocket` and in v2 do Kraken-way).

So yeah, I'd like to understand if you see it as subprotocol of websocket, or rather something separate

**Comment by Crain-32** [comment]
@derberg STOMP is in the club that just wants the connection. It's more of bi-directional protocol at heart, like your article mentioned though, Websocket is the defacto bi-directional communication. Regarding Kraken, that looks like a Custom protocol that just passes JSON objects around. I didn't look into it too much though, just enough to say it is not STOMP.

For the example, I took one of the Studio Templates and heavily modified it. The below would be an example of a simple messaging server that can support groups messages, and private messages.  [Example File](https://github.com/asyncapi/spec/files/8766788/stomp-example.txt)

When I was working on the example Doc, I modified the Bindings as the use case changed. They don't follow the original post that well anymore, but this is thankfully the stage of the discussion to have them be less defined.

STOMP works best by leveraging defaults, I'll use `channel` bindings as an example. For reference, I'll be using `publish` as the Server posting to the channel, with `subscribe` as the client posting to the channel. 
For any Publishing Channel, the Client can only receive Frames by first sending a `SUBSCRIBE` frame to the Channel. If we don't build that in as a default, you end up with the following. (And this isn't covering all the cases, just a basic Channel Subscription)
```yaml
/channel:
  publish:
    bindings:
       stomp:
         command: ["MESSAGE"]
    message:
         $ref:  '#/components/messages/mycoolmessage'
  subscribe:
    bindings:
      stomp:
        command: ["SUBSCRIBE", "UNSUBSCRIBE"]
      message:
         - oneOf
           - $ref: '#/components/messages/subscribe-frame'
           - $ref: '#/components/messages/unsubscribe-frame'
         bindings:
           stomp:
             headers:
               extra-header: "Value"
```
Ideally a Binding would handle this instead, as it would turn it into the below.
```yaml
/channel:
  publish:
    bindings:
       stomp:
         command: ["MESSAGE"]
         subscribable: true
    message:
         $ref:  '#/components/messages/mycoolmessage'
```
This Operation binding then allows us to be implicit with the Subscribing. The only issue from a STOMP Protocol/Binding sense is it doesn't easily allow for Custom Headers to be put into those frames. (`SUBSCRIBE` and `UNSUBSCRIBE` are thankfully not allowed to have Frame Bodies) There are other Frame Commands that situations like that (`ACK`, `NACK`, `RECEIPT`, etc) where it's really just better to have some sort of default, otherwise the Document could triple in size just to be "Accurate". That would be a similar argument to putting your `4XX`/`5XX` status returns in all your Open API endpoints though, which obviously is not the best idea.

If you have 15-30 minutes, I recommend reading the [STOMP Protocol Specs](https://stomp.github.io/stomp-specification-1.2.htm). That will hopefully help clarify what sort of default situations I'm talking about.

*PS, after writing all this, I realized a potential for Channel Bindings to handle defaults instead of Operation Bindings could be something like this*
```yaml
bindings:
  stomp:
    server: true
    commands:
      subscribe:
        headers:
          extra-header: "value"
      unsubscribe:
        headers:
          extra-header: "value"
```
*Instead of `subscribable`, we swap to `server`, which is just to declare the channel can be Subscribed to, and then we declare any extra header values these channel commands could have within the `commands` property.*

**Comment by Crain-32** [comment]
@derberg I was thinking about how to make the bindings easier to categorize, and I think part of the issue is there isn't a good separation between what should be assumed about the protocol by someone using a Binding, and what needs to be specified by the Binding.

For example when creating a basic [Java SpringBoot STOMP Broker](https://docs.spring.io/spring-framework/docs/current/reference/html/web.html#websocket-stomp), STOMP is explicitly stated as a sub-protocol of Websockets, you have to enable an HTTP endpoint to do the Upgrade Handshake (Which is also where Spring Recommends you handle initial Authentication). You can see in my proposal/example that there isn't any binding that would support marking the handshake, as in my opinion the Handshake isn't part of STOMP, but rather part of the Parent Protocol of the Websocket.

This also answers the question of "Is STOMP a Sub-Protocol of the Websocket, or separate", it is a Sub-Protocol. 

To help fix the issue of WebSocket Sub-Protocols in mind, I believe we should add a new Field in the WebSocket's Channel Binding. Which I propose to be the following.

Field Name: `enablesSubProtocol`
Type: `string`
Description: `The Sub-Protocol that will take over all further communication after a Successful Handshake`
YAML -
```yaml
bindings:
  ws:
    enablesSubProtocol: "STOMP"
```
JSON - 
```json
"bindings": {
  "ws": {
    "enablesSubProtocol": "STOMP"
  }
}
```

I can't find anything clear in AsyncAPI about handling Sub-Protocols. If I'm wrong about that feel free to send a link so I can update my example. For now I think we should put STOMP on hold until we have a clear handling on marking the Sub-Protocols' Handshake Channel, and how much of a Protocol should be "assumed" by the Spec. After which STOMP should be easier to move forward with.

**Comment by fmvilas** [comment]
> Nice Issue @Crain-32! 🥇 💯

I fully agree. Thanks for the great explanation.

> But there is a constraint: only one protocol can be defined on a server protocol field.

@smoya What about using something like `ws+stomp` as the protocol? This would make it clear that it's using a combination of both. In this case, should we make it clear that the protocol field could be a composition of protocols separated by `+`?

**Comment by smoya** [comment]
> @smoya What about using something like `ws+stomp` as the protocol?

I thought about that possible solution but then we would need to somehow extend the STOMP bindings from the Websockets one, isn't? It adds more complexity; not saying it is a bad solution at all.

**Comment by derberg** [comment]
let me add a bit more to this discussion.

but first in short: why not adding a new `subprotocol` (or actually `subprotocols` at [technically more than one can be supported](https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism))  field to WebSocket binding + specify separately all fields needed for `stomp` binding separately. And in `subprotocol` we would say what protocol is it and user ref, to just follow what was specified in the `stomp` binding?

Subprotocol usage in WebSocket is standard, where WebSocket is just a transport, and it is not only about `stomp`, but:
- `wamp` -> https://github.com/asyncapi/spec/issues/400
- MQTT usage over WebSocket

so yeah, primary is `WebSocket`, and `subprotocol` is its feature, so sounds to me like we need:
- new field in websocket binding
- stomp, wamp and other protocols (mqtt is there already) described as standalone bindings and reused in websocket

🤔

**Comment by smoya** [comment]
> so yeah, primary is `WebSocket`, and `subprotocol` is its feature, so sounds to me like we need:
> 
> * new field in websocket binding
> * stomp, wamp and other protocols (mqtt is there already) described as standalone bindings and reused in websocket

Isn't that what I mentioned in https://github.com/asyncapi/spec/issues/787#issuecomment-1167538551 ?

**Comment by Crain-32** [comment]
@smoya Apologizes for getting back to you so late on this! I completely forgot your last comment, so this latest spark in the conversation reminded me.

The clarification about the STOMP being the messaging framework, while WebSockets serve as the transportation is a good one, thanks for bringing that up.

I'm torn between the implementation examples provided in comment [#787](https://github.com/asyncapi/spec/issues/787#issuecomment-1167538551), as although I like showing the Server is using WebSockets for transportation, I don't like the idea of WebSockets "owning" Stomp.  From my perspective I'm connecting to a STOMP server over WebSocket, not communicating with a WebSocket server using STOMP.

**Comment by smoya** [comment]
> From my perspective I'm connecting to a STOMP server over WebSocket, not communicating with a WebSocket server using STOMP.

No problem @Crain-32! I edited my [previous comment](https://github.com/asyncapi/spec/issues/787#issuecomment-1175481699) to clarify that my concern was in sync with yours. The definition says that the protocol defines how do you interchange messages (API), not how you connect. So indeed, **STOMP** seems to be the protocol in this case.

However, the `protocol` field on [ServerObject](https://www.asyncapi.com/docs/reference/specification/v2.4.0#serverObject) is described as:

> The protocol this URL supports for connection. 

Then, it means a protocol **should** also take care of the connectivity (wire).
A solution like the one @fmvilas suggests on https://github.com/asyncapi/spec/issues/787#issuecomment-1173663381 seems the most appropriate then.

Does it make sense? @Crain-32 @derberg @fmvilas

**Comment by derberg** [comment]
@smoya 

> Isn't that what I mentioned in https://github.com/asyncapi/spec/issues/787#issuecomment-1167538551 ?

I understood from your comment, that `ws` is next to `stomp` (technically in the document, as 2 separate bindings). While in my comment I write that `stomp` and others could be referenced inside `ws` in a new field called `subprotocols`.

On a server level, you need information on how to connect:
- `headers` that are now in `ws` binding should go to `Server Object` and this is where you specify how user should establish a connection, that you need to pass in the header info about subprotocol
- more info about subprotocol, you put using `stomp` or `wamp` binding, but inside `ws` in `subprotocols` list. I think it is just more elegant and straightforward, especially for the tooling implementation, but also for a human eye. Example - if I provide `ws` and `stomp` bindings next to each other, but do not specify `headers` related to subprotocol in `ws`, or I do not provide suggested `enablesSubProtocol` in `ws`...then what does it mean, should I assume `stomp` is a subprotocol?

🤔

**Comment by smoya** [comment]
> stomp and others could be referenced inside ws in a new field called subprotocols.

Now I realize you meant to use `$ref` under `subprotocols` field to reference the `stomp` protocol declared somewhere else. I like it 👍. However, we need to clarify a couple of behaviors that might create confusion. First, let me add a simple example:

```yaml
servers:
  public:
    url: wss://api.gemini.com
    protocol: wss
    bindings:
      ws:
        subprotocols:
          - $ref: "#/servers/public/bindings/stomp"
      stomp:
        version: v12
        login: my-user
        passcode: ${my-user-passcode}
```

Notice the `version` field in the `stomp` protocol.  Somehow, b It means the header in the `ws first connection `Sec-WebSocket-Protocol` should be "Sec-WebSocket-Protocol: v12.stomp" as per IANA https://www.iana.org/assignments/websocket/websocket.xml.

This could collide in case the user redefines the `Sec-WebSocket-Protocol` header, for including a protocol that doesn't exist yet as binding (i.e.`xmpp`) . For example:

```yaml
servers:
  public:
    url: wss://api.gemini.com
    protocol: wss
    bindings:
      ws:
        headers: 
          type: object
          properties:
            Sec-WebSocket-Protocol:
              enum:
                - xmpp 
                - # what about v12.stomp, is it inferred from the subprotocols field?
        subprotocols:
          - $ref: "#/servers/public/bindings/stomp"
      stomp:
        version: v12
        login: my-user
        passcode: ${my-user-passcode}
```

This introduces confusion on the final solution. The same if someone, for example, adds `v11.stomp` as `Sec-WebSocket-Protocol` but then the `stomp` binding `version` field says `v12`. 
I agree tooling could eventually do the job on validating, but this is not feasible atm.

**Comment by thushalya** [comment]
So for now I have to specify the subprotocol as a  header in  "Sec-WebSocket-Protocol" field?. I just want to specify GraphQL over Web Socket subprotocol in AsyncAPI spec. is it like this for now?


`asyncapi: 2.5.0
info:
  title: GraphQLOverWebSocket
  version: 1.0.0
channels:
    / :
    publish:
      ...

    subscribe:
      ...

    bindings:
        ws:
          headers:
             type: object
             properties:
                 Sec-WebSocket-Protocol:
                    enum:
                       - graphql-transport-ws `
