### ISSUE TITLE
[📑 Docs]: In AsyncAPI Specification docs, Should we format the keywords in a bulleted list? 

### ISSUE THREAD

**Issue by pratik2315** [asyncapi/spec#788]
### What Dev Docs changes are you proposing?

**In the Specification 2.3.0 the keywords "MUST", "MUST NOT" etc. are given: https://www.asyncapi.com/docs/specifications/v2.3.0**

![Screenshot (50)](https://user-images.githubusercontent.com/77961530/165929653-c1c255c7-f08e-4bc8-8b9a-969c4c9d087d.png)

**IMHO, We could format and restructure them in a better way by listing them. Something similar like this:**
![Screenshot (47)](https://user-images.githubusercontent.com/77961530/165930786-844a28a8-ad92-49e9-9c5b-3c39eeb47395.png)

The current format looks a bit crowded. I think by formatting the keywords the user can have a better experience reading the docs. 

We can even opt to remove double quotes if they aren't necessary? What do you guys think ?

Would love to hear everyone's views on this :) 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fmvilas** [comment]
I just left a comment at https://github.com/asyncapi/spec/pull/790#pullrequestreview-976083994 explaining why this shouldn't be done in the spec. Please remember the spec is a normative document and not strictly documentation as we usually understand it.

**Comment by octonawish-akcodes** [comment]
So Is this issue still open @derberg @alequetzalli @fmvilas

**Comment by derberg** [comment]
@octonawish-akcodes thanks for ping. As stated https://github.com/asyncapi/spec/pull/790#pullrequestreview-976083994 we should not make this change. closing the issues
