### ISSUE TITLE
Extend workflow responsible for spec update in website repo with `button` addition

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#789]
With each release now, we would have to do https://github.com/asyncapi/website/pull/720

The manual changes introduced in ☝🏼 PR should be automated, basically [this](https://github.com/asyncapi/spec/blob/master/.github/workflows/new-spec-release.yml) workflow needs to be extended.

**Comment by saigoud25** [comment]
hey, I want to work on this. Can you please specify on which file to work?

**Comment by derberg** [comment]
@saigoud25 Thanks!

edit must be done in these 2 files:
- https://github.com/asyncapi/spec/blob/master/.github/workflows/new-spec-release.yml
- https://github.com/asyncapi/spec/blob/master/.github/workflows/update-spec.yaml

father step "Copy Spec file from Current Repo to Another" and before table of contents removal. Best if you refactor https://github.com/asyncapi/spec/blob/master/.github/scripts/remove-toc.js that already does read the spec file, so you would not have to create new script with the same functionality. Jsut rename `remove-toc.js` to something more generic and have there a function for ToC removal, and add new function that adds button at the end of the spec file.

Of course ask if you need more help 🍺

**Comment by Shofiya2003** [comment]
Can I take up this issue?
I would like to work on it.

**Comment by Shofiya2003** [comment]
@derberg does  [this PR](https://github.com/asyncapi/website/pull/1188) solve this issue, or we will still need changes in the workflow files?

**Comment by derberg** [comment]
@Shofiya2003 yup, https://github.com/asyncapi/website/pull/1188 solves this issue, thanks for the info
