### ISSUE TITLE
Servers Object Question

### ISSUE THREAD

**Issue by VisualBean** [asyncapi/spec#805]
### Is the Servers object, to be considered an Object or a Collection?

> ... we want to keep as much compatibility as possible with the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification).

Looking at the OpenAPI Documentation, Servers can be either a single object
```json
{
  "url": "https://development.gigantic-server.com/v1",
  "description": "Development server"
}
```

or a collection 
```json
{
  "servers": [ // Notice the array notation..
    {
      "url": "https://development.gigantic-server.com/v1",
      "description": "Development server"
    },
    {
      "url": "https://staging.gigantic-server.com/v1",
      "description": "Staging server"
    },
    {
      "url": "https://api.gigantic-server.com/v1",
      "description": "Production server"
    }
  ]
}
```

But looking at the documentation for AsyncAPI it is always an object.
```json
{
  "servers": { // No array notation, rather an object with multiple properties.
    "development": { 
      "url": "development.gigantic-server.com",
      "description": "Development server",
      "protocol": "amqp",
      "protocolVersion": "0.9.1"
    },
    "staging": {
      "url": "staging.gigantic-server.com",
      "description": "Staging server",
      "protocol": "amqp",
      "protocolVersion": "0.9.1"
    },
    "production": {
      "url": "api.gigantic-server.com",
      "description": "Production server",
      "protocol": "amqp",
      "protocolVersion": "0.9.1"
    }
  }
}
```

Is it merely a documentation mistake, or is it to be consideren an object always?
- I was hoping that AsyncAPI would stay consistent with OpenAPI for most of the "same" metadata structures.

(working on a (de)serializer for dotnet)

**Comment by magicmatatjahu** [comment]
@VisualBean Hi! Servers in the AsyncAPI are a map, where the key is the "name" of the server and the value is the detail of server. We don't use semantic from OpenAPI in `servers` section.

**Comment by VisualBean** [comment]
Thank you for the quick reply

**Comment by magicmatatjahu** [comment]
@VisualBean No problem :) I think that we can close that issue, yes? 

For you know, we try to reuse the object structures from OpenAPI, but our servers have information about the protocol, its version and bindings and this structure has to be different than OpenAPI introduces.

@derberg Could you close it?
