### ISSUE TITLE
schema object: type as string | array, plan to align with OpenAPI Schema Object?

### ISSUE THREAD

**Issue by VisualBean** [asyncapi/spec#817]
Background: 
I am working on a serializer/deserializer library for AsyncAPI particularly in the Dotnet space.

The JsonSchema validation spec specifies the following:
> [6.1.1. ](https://json-schema.org/draft/2020-12/json-schema-validation.html#section-6.1.1)[type](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-type)
The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.

The OpenAPI specification, has deliberately mentioned Type only being supported as a string (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#schema-object)
>type - Value MUST be a string. Multiple types via an array are not supported.

I see the AsyncAPI specification, does not do this specifically.

I heard one of the reasons for OpenAPI to not support multiple types had to do with typed language support.

Is there a plan to align this particular property of the Schema Object, with the OpenAPI specification?

**Comment by magicmatatjahu** [comment]
@VisualBean OpenAPIs < 3.1.0 use their own JSON Schema (based on some old draft, probably 04), but 3.1.0 uses the latest one, when you can define types as array (https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#schema-object). In AsyncAPI we use JSON Schema draft 07 (with our additional keywords like externalDocs, deprecated and discriminator). We don't have a plan to align this property with OpenAPI <3.1.0

**Comment by VisualBean** [comment]
I see i was looking at older versions. 

Thanks for the clarification

**Comment by magicmatatjahu** [comment]
@derberg @fmvilas Could someone from you close that issue?
