### ISSUE TITLE
Work on 2.5.0 release

### ISSUE THREAD

**Issue by char0n** [asyncapi/spec#830]
Release 2.5.0 is scheduled for September 2022

### Detailed info:

* https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md

Assigned release coordinator and person responsible for the 2.5.0 release: @char0n

### Kick-off:

* **TODO**: incorporate release plan described by this issue in one of the September community meetings

### Release branches:

* https://github.com/asyncapi/spec/tree/next-spec
* https://github.com/asyncapi/spec-json-schemas/tree/next-spec
* https://github.com/asyncapi/parser-js/tree/next-spec
* https://github.com/asyncapi/bindings/tree/master

### Release notes:

* draft PR - https://github.com/asyncapi/website/pull/PULLREQUEST

#### Accepted

- [x] https://github.com/asyncapi/spec/issues/775
  - [x] https://github.com/asyncapi/spec/pull/776
- [x] https://github.com/asyncapi/spec/issues/654
  - [x] https://github.com/asyncapi/spec/pull/809
  - [x] https://github.com/asyncapi/spec-json-schemas/pull/232
  - [x] https://github.com/asyncapi/parser-js/pull/565
- [x] Missing IBMMQ Operation Binding
  - [x] https://github.com/asyncapi/spec/pull/840
  - [x] https://github.com/asyncapi/bindings/pull/149
- [x] Google Pub/Sub bindings
  - [x] https://github.com/asyncapi/bindings/pull/141
  - [x] https://github.com/asyncapi/spec/pull/836
  - [x] https://github.com/asyncapi/spec-json-schemas/pull/253
- [x] https://github.com/asyncapi/spec/issues/612 (editorial change)
  - [x] https://github.com/asyncapi/spec/pull/779
- [x] https://github.com/asyncapi/spec/issues/674 (editorial change)
  - [x] https://github.com/asyncapi/spec/pull/782
- [x] https://github.com/asyncapi/spec/pull/818 (editorial change)
- [x] https://github.com/asyncapi/spec/pull/832 (editorial change)
- [x] https://github.com/asyncapi/bindings/pull/115

#### Discarded

- [x] https://github.com/asyncapi/bindings/pull/143
- [x] https://github.com/asyncapi/spec/pull/826
- [x] https://github.com/asyncapi/spec/pull/595
- [x] https://github.com/asyncapi/spec/pull/790

### Progress:
- [x] Update release branches from forks
    - [x] spec - https://github.com/asyncapi/spec/pull/831
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/249
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/606
- [x] Update release branches with new versions
    - [x] spec - https://github.com/asyncapi/spec/pull/808
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/230, https://github.com/asyncapi/spec-json-schemas/pull/250
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/617
- [x] Create draft release notes
- [x] Notify community about release branches
- [x]  Notify code owners of critical repositories about the pre-releases
- [x] Check for potential release contributions
- [x] Draft announcement blog post for new features and changes - https://github.com/asyncapi/website/pull/959
- [x] Write release notes for new features and changes
- [x] Notify tsc_members about upcoming release
- [x] Prepare pull requests to merge release branches into master
    - [x] spec - https://github.com/asyncapi/spec/pull/842
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/265
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/627
- [x] Merge release branches into master
    - [x] spec
    - [x] spec-json-schemas
    - [x] parser-js
- [x] Write release notes for the releases on Github
- [x] Create releases on Github
    - [x] spec
    - [x] spec-json-schemas
    - [x] parser-js
- [ ] Update RELEASE_PROCESS doc with any changes

### Draft release notes

```md
Release notes article -> https://www.asyncapi.com/blog/release-notes-2.5.0

Features
---
- Server Variables can be now referenced from inside the Server Object (#776) ([5deef1e](https://github.com/asyncapi/spec/commit/5deef1e9148947689d53db3a1d013d49cd9df7d0)), resolves #775 by @char0n 
- Decorating Server Object with tags (#809) ([b0c2f9c](https://github.com/asyncapi/spec/commit/b0c2f9c086d940e8016ec1fa60107fe74cc070db)), resolves #654, resolves #465 by @smoya
- Added new Google Cloud Pub/Sub Bindings (#836) ([babc3be](https://github.com/asyncapi/spec/commit/babc3bedb5d85375a305c7268e96257113c1933e)) ([binding definition](https://github.com/asyncapi/bindings/tree/master/googlepubsub)) by @whitlockjc 
- Added schema registry infos to Kafka binding ([#115](https://github.com/asyncapi/bindings/pull/115)) ([binding definition](https://github.com/asyncapi/bindings/tree/master/kafka)) by @lbroudoux
- Other enhancements
  - Clarified ChannelItem.$ref resolution rules (#779) ([9a293c7](https://github.com/asyncapi/spec/commit/9a293c77f6bf74a056a8845dabfbe20e73a6f320)), resolves #612 by @char0n
  - Clarification around URL resolution rules (#782) ([fc324ef](https://github.com/asyncapi/spec/commit/fc324ef3aa92d313918a00ea9a5eb6c85720a36d)), resolves #674 by @char0n
  - Align wording with [RFC 2119](https://www.rfc-editor.org/rfc/rfc2119) (#818) ([5580a9c](https://github.com/asyncapi/spec/commit/5580a9c5fbef55e925e7514b986c95a0e4c85821)) by @char0n

Fixes
---
- Added missing IBM MQ Operation Binding (#840) ([68d85d1](https://github.com/asyncapi/spec/commit/68d85d19e5be12fa6e13d0fc5851993934dbdcde)) ([binding definition](https://github.com/asyncapi/bindings/tree/master/ibmmq#operation-binding-object)), refs [#605](https://github.com/asyncapi/spec/issues/605) by @magicmatatjahu

Full Changelog: https://github.com/asyncapi/spec/compare/v2.4.0...v2.5.0
```

###### Guildeline how to write release notes

Referencing PRs, issues and commits respectively.

###### Close pre-release notifications issues on critical repos

- https://github.com/asyncapi/html-template/issues/375
- https://github.com/asyncapi/converter-js/issues/143
- https://github.com/asyncapi/asyncapi-react/issues/646
- https://github.com/asyncapi/studio/issues/431

###### Clarification about updating parser-js with pre-releases

> Important: When release candidates are created for the [spec](https://github.com/asyncapi/spec) repository, the [parser-js](https://github.com/asyncapi/parser-js) repository will need to be updated to use that release candidate.

######  Notify code owners of critical repositories about the pre-releases

This item needs to  be added to the check list.

###### Notify community about release branches

The branches are not created at ad-hoc basis anymore. To this step might not be necessary anymore.

###### Bindings

I've added https://github.com/asyncapi/bindings/tree/next-major into  a **Release branches**. We should probably think about using latest JSON Schemas after a new release inside the bindings JSON Schemas as suggested in https://github.com/asyncapi/bindings/pull/143/files. This is a candidate for a cleanup task.

###### Creating release branches

In a light of https://github.com/asyncapi/spec/issues/734, creating a release branches is no longer necessary. Following TODO items can be removed from the [release issue template](https://github.com/asyncapi/spec/blob/master/.github/ISSUE_TEMPLATE/release.md). I've also took liberty of removing following items from this issue progress tracker:
- [ ] Create release branches
    - [ ] spec
    - [ ] spec-json-schemas
    - [ ] parser-js

This is a candidate for a cleanup task.

###### Updating default branches with release branch name

In a light of https://github.com/asyncapi/spec/issues/734, updating default branches with release branch name is no longer necessary. Following TODO items can be removed from the [release issue template](https://github.com/asyncapi/spec/blob/master/.github/ISSUE_TEMPLATE/release.md). I've also took liberty of removing following items from this issue progress tracker:
- [ ] Update default branches with release branch name
    - [ ] spec
    - [ ] spec-json-schemas
    - [ ] parser-js

This is a candidate for a cleanup task.

###### Auto-update `next-spec` branches automatically

Ref https://github.com/asyncapi/spec-json-schemas/pull/249#pullrequestreview-1106369882

This is a candidate for a cleanup task.

###### Bad link in release process document

![image](https://user-images.githubusercontent.com/193286/192716885-9c144e81-8dc7-4065-8042-d037b515e311.png)

There are two things wrong with this. The PRs shouldn't be created in `Draft` mode and the link is invalid. Along with that, other links doesn't work as well as numbering has been probably changed in past which invalidated the link anchors.

###### Step 5 - create pull requests

This step was not clear. I understood it in a way to create a PR from a fork - in order to resolve the conflics.

**Comment by char0n** [comment]
Pre-releases are currently not auto-generated due to  https://github.com/asyncapi/spec/pull/834.

**Comment by char0n** [comment]
Pre-releases of schemas are currently not auto-generated due to https://github.com/asyncapi/spec-json-schemas/pull/255.

**Comment by char0n** [comment]
Pre-release global workflow modification in https://github.com/asyncapi/.github/pull/180

**Comment by magicmatatjahu** [comment]
Can we add that PR to the list? https://github.com/asyncapi/spec/pull/840 Thanks!

**Comment by derberg** [comment]
ok, another improvement after release that we need is to set branch protection on the release branches since these are not "stable" in the way that name doesn't change. This way, we make sure @fmvilas is not able to do a force push on these next time 😆

**Comment by fmvilas** [comment]
You do realize that I can enable force-push back and then do it again, right? :trollface: Now seriously, sorry for all the noise 😅

**Comment by char0n** [comment]
AsyncAPI 2.5.0 release - https://github.com/asyncapi/spec/releases/tag/v2.5.0

**Comment by char0n** [comment]
JSON Schemas release -  https://github.com/asyncapi/spec-json-schemas/releases/tag/v3.2.0

**Comment by char0n** [comment]
Parser-js - https://github.com/asyncapi/parser-js/releases/tag/v1.17.0

**Comment by char0n** [comment]
AsyncAPI 2.5.0 has been **successfully released**.

**Comment by derberg** [comment]
Another improvement in the process. The pull request with release notes blog in `website` repo should not only introduce the article itself but also changes in docs. We keep forgetting that, and as a result, [we have `2.2.0` promoted in the docs](https://www.asyncapi.com/docs/tutorials/getting-started/hello-world).

**Comment by char0n** [comment]
Resuming processing improvements now and incorporating them into https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md

**Comment by char0n** [comment]
Social media examples https://github.com/asyncapi/spec/pull/876/files

**Comment by jonaslagoni** [comment]
Any reason this is still open 🤔 ?

**Comment by derberg** [comment]
@char0n can you have a look?
