### ISSUE TITLE
Sergio joining as code owner

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec#844]
Hey fellow code owners @derberg, @dalelane, and @asyncapi-bot-eve 😄 

I'd like to propose that @smoya joins us as a code owner of the `spec` and `spec-json-schemas` repo. I think it's obvious how much he's been contributing lately and he deserves it IMHO. @smoya I hope you also want to accept this (questionable) honor :)

Leave your comments below!

**Comment by smoya** [comment]
It would be an honour, totally! ❤️

**Comment by dalelane** [comment]
totally agree 100% 👍

**Comment by derberg** [comment]
definitely agree, no question about it.
Sergio not only contributed to 2.4 as coordinator but also improved the spec itself a lot with many PRs and participates in review process a lot
