### ISSUE TITLE
Vladimir joining as code owner

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/spec#845]
Hey fellow code owners @derberg and @dalelane,

I'd like to propose that @char0n joins us as a code owner of the `spec` and `spec-json-schemas` repo. I think it's obvious how much he's been contributing lately and he deserves it IMHO. @char0n I hope you also want to accept this (questionable) honor :)

Leave your comments below!

**Comment by dalelane** [comment]
absolutely agree - even just looking at the latest contribution, the 2.5.0 release was a great piece of work - but that's on top of loads of other contributions

**Comment by char0n** [comment]
Thank you all for the trust. I do accept and I'll do my best ;]

One question though: Does this automatically also make me the [TSC member](https://www.asyncapi.com/community/tsc) or being a code owner is unrelated to TSC membership?

**Comment by smoya** [comment]
> One question though: Does this automatically also make me the [TSC member](https://www.asyncapi.com/community/tsc) or being a code owner is unrelated to TSC membership?

This is exactly one of the requirements you might fulfill to become TSC member. So, yes 👍

**Comment by fmvilas** [comment]
Yup. The TSC is composed of all the code owners of the organization. There are exceptions like a) someone doesn't want to join, and b) someone belongs to an organization that already surpassed the limit (1/4 of the total members count). Not your case so you're welcome to join the TSC. Would you mind adding yourself to https://github.com/asyncapi/community/blob/master/TSC_MEMBERS.json?
