### ISSUE TITLE
Should we do branch protection on release branches?

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#861]
**Current State**

We have branch protection on `master` only.
So in release branches:
- maintainers can do force push
- we can merge PRs to these when CI fails
- changes in PRs after approval do not discard approvals. So in theory bad actor can push changes to PR without approvals before merging it

**Future**

Should we set up the same branch protection rules for release branches that we have in the `master` branch already?
And if we set these, we should do it also in release-related repos like `spec-json-schema` and `parser-js`

** Current settings for reference**
![Screenshot 2022-10-26 at 18 21 07](https://user-images.githubusercontent.com/6995927/198080720-0782e585-bcc4-4ddf-87bd-f146d55a408a.png)

cc codeowners @dalelane @char0n @smoya @fmvilas 

I personally thing we should enable branch protection for release branches, as there is no benefit of not having these

**Comment by jonaslagoni** [comment]
Definitely think you should add them yes 👍

**Comment by fmvilas** [comment]
Yup 👍

**Comment by dalelane** [comment]
yup - agreed. 

Easier to enforce what we want to happen rather than rely on people remembering what's agreed

**Comment by smoya** [comment]
I think we should 👍

**Comment by derberg** [comment]
Branch protection for `*next*` (which means any branch with `next` in the name) is now set.
It is set in all release critical repos, spec, spec schema and parser
