### ISSUE TITLE
Are extensions allowed inside bindings?

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#869]
my opinion: Yes, should be

But this is not documented.

#### Current situation
- AsyncAPI spec described in markdown file do not say anything about it
- Bindings specs described in markdown file do not say anything about it
- because we assumed bindings should support extensions, JSON Schema files for bindings allow usage of `x-` extensions

#### Proposal

It should not be something that is agreed upon per binding, but it should be written down in AsyncAPI spec that each binding should support extensions

Thoughts?

**Comment by char0n** [comment]
> AsyncAPI spec described in markdown file do not say anything about it

As a tooling author I assumed that extensions are not supported, given that spec, nor individual binding objects contain the following sentence: `This object MAY be extended with Specification Extensions.`

> because we assumed bindings should support extensions, JSON Schema files for bindings allow usage of x- extensions

I assumed the opposite as I considered the markdown spec as single source of truth and not the schemas. 

> It should not be something that is agreed upon per binding, but it should be written down in AsyncAPI spec that each binding should support extensions

Agreed.

---

Overall IMHO it's a good idea for individual binding objects to support extensions and to specify it explicitly in the markdown spec file.

**Comment by char0n** [comment]
One more note: binding objects would need to be inspected as for example `amqp` Channel Binding Object look like this:

![image](https://user-images.githubusercontent.com/193286/199692517-4db48b92-1247-4a7a-8d0d-523dfcc6166d.png)

Notice the footer: `This object MUST contain only the properties defined above.`

**Comment by jonaslagoni** [comment]
I actually thought it was supported.

Dont see anything wrong in adding support for it, as it gives you the option to play around with different setups before proposing the changes to the binding.

**Comment by fmvilas** [comment]
> @fmvilas before I open a PR, do you remember why it was not added to the spec in the first place? don't want to work on a PR of there was already some discussion about it.

I don't. Most probably it was simply missed.
