### ISSUE TITLE
Release schedule of spec 3.0

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#880]
Up until now, we have slowly worked our way through issues and slowly progressed as time went on, but now it seems there is consensus to get "down to business".

In the [last meeting](https://www.youtube.com/watch?v=qgcRg5sVOKg), we discussed setting the release date and freeze period for when the last change to the spec can happen. This issue finalizing that proposal, and this is only a proposal and not an order 😄 

Remember we do not have a targetted scope for spec 3.0, the scope is what has reached RFC stage 3 at the time of the release. Read more about the RFC process in the [contributing guide](https://github.com/asyncapi/spec/blob/master/CONTRIBUTING.md). 

Therefore this release schedule suggests a specific release period and a freeze period to give people an adequate amount of time to review the final version before it's released.

## Release 3.0.0 is scheduled for June 2023
The suggestion is to release spec 3.0 at the end of June next year (in the second release period), and whatever proposals has reached RFC stage 3, at that time will be included in version 3. 

## Freeze period from February 2023
The suggestion is from the end of February no more new changes are allowed into spec 3.0, from then on it's only about finalizing what we have. That means that any proposals that have not reached RFC stage 2 (should it be stage 1?) will not be included in spec 3.0, regardless of whether they finish between February and the end of June.

What this means is that the only change that can happen from February onwards are:
- Review and minor edits of existing changes.
- Finalizing tooling implementations in the parser and JSON-schema-spec repository to reach stage 3 (as stage 2 does not mean the implementations are finalized).
- Removal of existing features that are deemed rejected.

**Comment by jonaslagoni** [comment]
> I also think we should define some must-haves for the release. Release notes and schema + parser are not enough for 3.0

@derberg I think that is a completely valid point, let's see who wants to chip in.

Here is the list of things I seek out to make sure is updated for v3 (either through good first issues or manually do them)
- Generator 
- Modelina (otherwise some code templates cant update)
- All templates (it will be somewhat of a major task to convert them, but then again I don't think it's that bad) 
- EDAVisualiser

I also think that when the spec freeze happens, we can do spec v3 office hours where maintainers can get help updating their implementation, or contributors can get help solving the update issues.

Thoughts?

**Comment by derberg** [comment]
I like office hours idea, it will be needed also for docs contributors.

Not sure if all templates need to be migrated but for sure:
- converter
- studio
- react component -> html teplmate

**Comment by fmvilas** [comment]
I'm all in with the freeze period starting on March 1st this year. Whatever is complete is in, otherwise, it's not.

**Comment by jessemenning** [comment]
I'm in favor of the March 1 freeze, but would strongly support #881 being addressed in v3

**Comment by jonaslagoni** [comment]
After the [last meeting](https://github.com/asyncapi/community/issues/599) we discussed this issue and suggest the following.

We keep the proposed deadlines but make an exception to two proposals, as they are already well underway and are breaking changes:
- https://github.com/asyncapi/spec/issues/622
- https://github.com/asyncapi/spec/issues/505

As we are already past the deadline for when this should take effect, you have until [the next spec 3.0 meeting](https://github.com/asyncapi/community/issues/624) (March 15) to reject this, otherwise lazy consensus applies cc code owners @char0n @fmvilas @derberg @dalelane @smoya.

**Comment by jonaslagoni** [comment]
Replaced by https://github.com/asyncapi/spec/issues/944
