### ISSUE TITLE
Cleanup readme with icons of sponsors

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#883]
- README has outdated info about current sponsors
- According to [Open Collective](https://opencollective.com/asyncapi) sponsor tiers, every sponsor, platinum, gold, silver should be mentioned in GitHub readme
- We need 3 headings, Platinum, Gold and Silver like we have on asyncapi.com and put there logos of current sponsors
- https://www.asyncapi.com/ is source of truth. For example in OC RedHat appears as Bronze, but they are Gold as in expenses it is clear they pay 1k every month
- Silver - there is a new sponsor, bump.sh -> https://github.com/asyncapi/website/issues/1158

**Comment by ChristopheDujarric** [comment]
Here is the Bump.sh logo ![bump-logo-black](https://user-images.githubusercontent.com/7700560/207550933-3a26c83a-c7a4-4a42-a242-9f84197eba7c.svg)
If possible, it would be amazing to have the link behind the logo include UTM tags as: https://bump.sh/asyncapi?utm_source=asyncapi&utm_medium=github_readme&utm_campaign=sponsor

**Comment by AnimeshKumar923** [comment]
Hello there!
I would like to work on this issue. I'm new to Open-Source world. If possible, please guide me through this.
Thank you!

**Comment by AnimeshKumar923** [comment]
where should I add Sponsors section in reamde.md?
above contributors?
below contributors? @derberg

**Comment by derberg** [comment]
I think it is fine to put it in the place where current logos are

![Screenshot 2022-12-14 at 11.34.41.png](https://volta.s3.fr-par.scw.cloud/Screenshot_2022_12_14_at_11_34_41_a0b3ec6934.png)

```
## Sponsors

### Platinum

### Gold

### Silver
```

use the same logos that are in https://deploy-preview-1159--asyncapi-website.netlify.app/ as Open Collective is not the only source.

Thanks!!!

**Comment by sambhavgupta0705** [comment]
Can we change the whole layout ,
we can go like this 

`Sponsors

Platinum Sponsors

Gold

Silver`

and then a message of join them

**Comment by derberg** [comment]
yup, just `Platinum` and not `Platinum Sponsors`

**Comment by derberg** [comment]
Solved with https://github.com/asyncapi/spec/pull/886
