### ISSUE TITLE
Marking parameters as optional

### ISSUE THREAD

**Issue by awrb** [asyncapi/spec#885]
Hello,
if this was asked before, then sorry in advance, but I did not find it anywhere (which is weird, as it seems like a very basic feature):
is it possible to mark a parameter as optional? Looking at the [documentation](https://www.asyncapi.com/docs/reference/specification/v2.5.0#parameterObject), it doesn't seem to be the case.

In AsyncAPI studio, the `required` label appears by default next to all the parameters:
![image](https://user-images.githubusercontent.com/34817384/207578832-3dd5c43d-d267-4e4a-bc88-f3d7f67e050a.png)

and in asyncapi-react/library/src/containers/Channels/Parameter.tsx, it is hard-coded to be true:
```
export const Parameter: FunctionComponent<Props> = ({
  param: { description, location, schema },
  name = '',
}) => (
  <div className={bemClasses.element(`channel-parameter`)}>
    <header className={bemClasses.element(`channel-parameter-header`)}>
      {location && (
        <h4>
          {LOCATION_TEXT}: {location}
        </h4>
      )}
    </header>
    <div className={bemClasses.element(`channel-parameter-schema`)}>
      <SchemaComponent
        name={name}
        schema={schema}
        hideTitle={true}
        description={description}
        required={true} // parameters are always required
      />
    </div>
  </div>
);

```

**Comment by awrb** [comment]
@magicmatatjahu  I can clarify the use case. I guess our approach is not fully conventional so I can see the confusion. Some of the parameters in some channels are treated similarly to HTTP query parameters. In the documentation this is an example for a parameterized channel:
`"user/{userId}/signup"`
in our case, we sometimes support subscriptions to channels like:
`channelName?key1=value1&key2=value2`
and then the parameters are extracted and handled server-side, and only the `channelName` part is required.

**Comment by derberg** [comment]
Do I assume correctly that you are using WebSocket? I don't know any other place where query params are used.

**Comment by awrb** [comment]
@derberg Yes, we use WebSockets ([STOMP Over WebSocket](http://jmesnil.net/stomp-websocket/doc/), to be precise).

**Comment by fmvilas** [comment]
@awrb Query params must be specified in the WebSocket binding in your case: https://github.com/asyncapi/bindings/tree/master/websockets. By default, all query params there are optional. Actually, there's no way to make them required. If you think you'd need it, you can easily add it to the binding as it's still a work in progress.

**Comment by awrb** [comment]
Thanks @fmvilas, I think this points me in the right direction and the question/issue can be closed.

**Comment by fmvilas** [comment]
Awesome. Let us know if there's something that doesn't feel quite right. Bindings are still in version 0.x so we're quickly iterating on them.
