### ISSUE TITLE
Schema validation in generated code

### ISSUE THREAD

**Issue by mcrobbj** [asyncapi/spec#887]

**Comment by fmvilas** [comment]
Closing as it doesn't have any description and it's wrongly labeled as RFC 1. @mcrobbj please read our [contributors guide](https://github.com/asyncapi/community/blob/master/CONTRIBUTING.md) and update the issue description.

**Comment by mcrobbj** [comment]
@fmvilas sorry I thought it was pretty self explanatory.

I have elements in my schema
        status:
          type: string
          enum: [match, no_match_close, no_match, unavailable]
        accountName:
          type: string
          maxLength: 60
          pattern: ^(.{1,60})$
          example: John Thomas

The generated code should match the types in the schema, and have error handling for if the message elements are of the wrong type or don't match the regex (pattern).

**Comment by fmvilas** [comment]
@mcrobbj what tool are you using? This is the repo for the spec so there's no code generation here. Let me know the tool and we can move this issue to its appropriate repo.
