### ISSUE TITLE
Work on 2.6.0 release

### ISSUE THREAD

**Issue by AceTheCreator** [asyncapi/spec#894]
Release 2.6.0 is scheduled for January 2023

### Detailed info:
* https://github.com/asyncapi/spec/blob/master/RELEASE_PROCESS.md

### Kick-off:
[* _link to recording of community call where the new release was started_](https://www.youtube.com/watch?v=9lJY5NcLMKY)

### Release branches:
* https://github.com/asyncapi/spec/tree/next-spec
* https://github.com/asyncapi/spec-json-schemas/tree/next-spec
* https://github.com/asyncapi/parser-js/tree/next-spec

### Release notes:
* draft PR - https://github.com/asyncapi/website/pull/PULLREQUEST

### Progress:
- [x] Create release branches
    - [x] spec - https://github.com/asyncapi/spec/tree/next-spec
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/tree/next-spec
    - [x] parser-js - https://github.com/asyncapi/parser-js/tree/next-spec
- [x] Update release branches from forks
    - [x] spec - https://github.com/asyncapi/spec/pull/892
    - [x] spec-json-schemas - https://github.com/asyncapi/spec-json-schemas/pull/301
    - [x] parser-js - https://github.com/asyncapi/parser-js/pull/691
- [x] Update release branches with new versions
    - [x] spec https://github.com/asyncapi/spec/pull/895
    - [x] spec-json-schemas https://github.com/asyncapi/spec-json-schemas/pull/302
    - [x] parser-js https://github.com/asyncapi/parser-js/pull/696
- [x] Create draft release notes
- [x] Update release branches from forks
    - [x] spec https://github.com/asyncapi/spec/pull/901
    - [x] spec-json-schemas https://github.com/asyncapi/spec-json-schemas/pull/306
    - [x] parser-js https://github.com/asyncapi/parser-js/pull/706
- [x] Notify community about release branches
- [x] Check for potential release contributions
- [x] Draft announcement blog post for new features and changes https://github.com/asyncapi/website/pull/1282
- [x] Write release notes for new features and changes
- [x] Prepare pull requests to merge release branches into master
    - [x] spec https://github.com/asyncapi/spec/pull/902
    - [x] spec-json-schemas https://github.com/asyncapi/spec-json-schemas/pull/307
    - [x] parser-js https://github.com/asyncapi/parser-js/pull/707
- [x] Notify tsc_members about upcoming release
- [x] Merge release branches into master
    - [x] spec spec https://github.com/asyncapi/spec/pull/902
    - [x] spec-json-schemas https://github.com/asyncapi/spec-json-schemas/pull/307
    - [x] parser-js https://github.com/asyncapi/parser-js/pull/707
- [x] Write release notes for the releases on Github
- [x] Create releases on Github
    - [x] spec
    - [x] spec-json-schemas
    - [x] parser-js
- [ ] Update RELEASE_PROCESS doc with any changes

## Draft Release notes

```
https://www.asyncapi.com/blog/release-notes-2.6.0

Features
---
- Added Pulsar Bindings and Protocol to the Specification (#882) (35693fb](https://github.com/asyncapi/spec/commit/35693fb90e230b48a51df952a743a12408995dd1)) ([binding definition](https://github.com/asyncapi/bindings/tree/master/pulsar)) by @VisualBean  

Full Changelog: https://github.com/asyncapi/spec/compare/v2.5.0...v2.6.0
```

**Comment by magicmatatjahu** [comment]
PR in converter https://github.com/asyncapi/converter-js/pull/162

**Comment by derberg** [comment]
For the post release task we need to solve one problem that we had with this release. Now we have a long living `next-spec` branch that stays there forever. When we release candidates,  `next-spec` is tagged with RC name like for example `2.5.0-next-spec.4`. Then when we do a release, tag `2.5.0` is added to `master`. 

So what happened with this release was that for `2.6.0`, the release candidate on `next-spec` was `2.5.0-next-spec.5` instead of `2.6.0-next-spec.1`. 

```
[9:27:17 AM] [semantic-release] › ℹ  Found git tag v2.5.0-next-spec.4 associated with version 2.5.0-next-spec.4 on branch next-spec
```

And the reason was that there is no technical information `semantic-release` have no idea that the las tag is `v2.5.0`.

It is not possible to check why in previous releases we did not face this issue as logs on CI are not preserved that long.

**Comment by derberg** [comment]
Opened separate issue for ☝🏼 
https://github.com/asyncapi/spec/issues/899

**Comment by AceTheCreator** [comment]
@asyncapi/tsc_members There's a new release coming up

**Comment by AceTheCreator** [comment]
AsyncAPI V2.6.0 is finally out 🚀

I'm pinging code owners of the repositories affected so you can do the necessary updates.

- [CLI](https://github.com/asyncapi/cli)
- [HTML Template](https://github.com/asyncapi/html-template)
- [Converter](https://github.com/asyncapi/converter-js/)
- [AsyncAPI React](https://github.com/asyncapi/asyncapi-react/)
- [Studio](https://github.com/asyncapi/studio)

@derberg @magicmatatjahu @fmvilas @jonaslagoni @M3lkior @Souvikns @KhudaDad414 @smoya

**Comment by fmvilas** [comment]
@AceTheCreator I think we can close this issue, right?
