### ISSUE TITLE
Message delivery constraints specifications (at-least-once, exactly-once, ...)

### ISSUE THREAD

**Issue by MihanixA** [asyncapi/spec#896]
Is there a way to define message delivery policy constraints, like at-least-once, at-most-once or exactly-once, for a combination of channel and client, or for a whole channel? And if yes, then what are the best options to do so in your opinion? 

Is there a way to specify that a channel messages are order-dependent for the recipient? Basically whether do we need to process them one by one or processing in any order is ok (cumulative sum for example).

**Comment by MihanixA** [comment]
One more thing, 
often when subscribing to a channel the resulting state on the client-side is an accumulation of an each message from event stream of that channel.

It seems, that the structure of that data could also be a part of APIs contract and therefore should be defined in the schema as well. 

Is there a way to specify an accumulated data structure for the channel?

**Comment by derberg** [comment]
@MihanixA sorry for late response.

I think you are looking for a way to describe some protocol specific semantics, which is definitely possible with AsyncAPI, but for this you use `bindings` feature -> https://github.com/asyncapi/bindings
