### ISSUE TITLE
docs: Typo error in asyncapi.md

### ISSUE THREAD

**Issue by sambhavgupta0705** [asyncapi/spec#908]
### Describe the bug
There is a typing error in [asyncapi.md](https://github.com/asyncapi/spec/blob/master/spec/asyncapi.md) 

### To Reproduce
1. Create a document with '...'
2. Try to change to '....'
3. Try to validate the document doing '....'

### Sample document
If applicable, add an AsyncAPI document illustrating the problem.

### Screenshots
![image](https://user-images.githubusercontent.com/81870866/223330564-1b8ccd19-e183-4af1-9dd8-abd7b20a04a4.png)

**Comment by derberg** [comment]
@sambhavgupta0705 🦅 👀 

please open a PR 🙏🏼
