### ISSUE TITLE
Add official Protobuf schema format 

### ISSUE THREAD

**Issue by jonaslagoni** [asyncapi/spec#914]
**Description**

We discussed this in the following meeting: https://www.youtube.com/watch?v=8Yjles2pEHo

It would be nice to have official schemaFormat types for Protobuf, in order for all tooling to understand when protobuf is in use instead of each having their own understandable value.

https://github.com/GreenRover/proto-schema-parser uses the following:
- application/vnd.google.protobuf;version=2
- application/vnd.google.protobuf;version=3

Which makes sense to use.

**Comment by GreenRover** [comment]
Yes i like

**Comment by GreenRover** [comment]
Waiting for: https://github.com/orgs/asyncapi/discussions/643
to be migrated

**Comment by smoya** [comment]
> But as v3 is locked down, I would wait for the next spec release to add it to the table 🙂

We can resume the work then!

**Comment by smoya** [comment]
@jonaslagoni @GreenRover Are we gonna do this then?
