### ISSUE TITLE
[v3] Support multi format schemas in message headers

### ISSUE THREAD

**Issue by smoya** [asyncapi/spec#948]
### Description
The current v3 spec mentions that the [Message Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.12#messageObject) headers must be of type "object". Literally says: 

> Schema definition of the application headers. Schema MUST be of type "object". It MUST NOT define the protocol headers. If this is a [Schema Object](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.12#schemaObject), then the schemaFormat will be assumed to be "application/vnd.aai.asyncapi+json;version=asyncapi" where the version is equal to the [AsyncAPI Version String](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.12#A2SVersionString).

Since the introduction of the support of [multi-format schemas](https://github.com/asyncapi/spec/pull/910/files), message headers also support different schema formats. 
Then, in my head, reading the sentence `Schema MUST be of type "object".` sounds confusing to me, especially for formats like Avro, where (afaik) there is no such type but `record` iirc.
This constraint is also in place in the AsyncAPI JSON Schema documents describing the message object. See https://github.com/asyncapi/spec-json-schemas/blob/next-major-spec/definitions/3.0.0/messageObject.json#L21-L27

Is that restriction in place with the purpose of limiting and simplifying what a header looks like? Shall we keep it and update it according to different possible shapes depending on the format? Or rather, after the recent changes, should we get rid of it?

Relates to https://github.com/asyncapi/spec/issues/622

cc @GreenRover @dalelane @derberg @jonaslagoni @fmvilas

**Comment by derberg** [comment]
yeah, sounds like `Schema MUST be of type "object"` is just a left over that should be removed. I don't think it is needed.

**Comment by GreenRover** [comment]
I vote for keep headers to be only async-api schema formated. To keep it simple. I see no benefit from defining header for example as avro.

**Comment by GreenRover** [comment]
Ok, my memories slowly come back. I guess Fran brought an reasons that required non ansycapi-schema as header.
But you @smoya only have concerns about the wording?

What i wanted to say is: Schema MUST be of type "object".  
A headers have to be some kind of map. 
A string/number like in the body is not valid.

**Comment by smoya** [comment]
> But you @smoya only have concerns about the wording?

Not just wording. As I mentioned in the issue description, that statement goes further as it's in the messageObject JSON Schema https://github.com/asyncapi/spec-json-schemas/blob/next-major-spec/definitions/3.0.0/messageObject.json#L21-L27

**Comment by fmvilas** [comment]
I think we should leave the sentence `Schema MUST be of type "object"` but change it to be broader in terms of the schema formats it supports. For instance, `Schema MUST represent a map of key-value pairs.`.

> I guess Fran brought an reasons that required non ansycapi-schema as header.

We should be able to support, at least, Avro because that's what the majority of the Kafka folks are using. Making them write the same information in JSON Schema just to use it in AsyncAPI is not fair.

**Comment by smoya** [comment]
> Schema MUST represent a map of key-value pairs.

Sounds like a more generic term, also not tied to JSON Schema, which is the intention.

> We should be able to support, at least, Avro because that's what the majority of the Kafka folks are using. Making them write the same information in JSON Schema just to use it in AsyncAPI is not fair.

I would say we must support all of the schema formats anyway. This also simplifies the schemas and tooling IMHO. No special behavior or exceptions when treating schemas.

**Comment by smoya** [comment]
FYI, https://github.com/asyncapi/spec-json-schemas/pull/370 got merged and support for **all** multiple formats is also included for headers. 

If there is a strong reason to revert that, please feel free to say it. Otherwise, if all agree, we can close this issue.
