### ISSUE TITLE
Ensure consistency when using either `Application` or `API` terms

### ISSUE THREAD

**Issue by smoya** [asyncapi/spec#949]
### Description
Current spec (and also v3) mixes the terms `Application` and `API` (and derivatives) to refer to the same thing.

For example, some of the [Info Object](https://www.asyncapi.com/docs/reference/specification/v2.6.0#infoObject) fields say:

> title: The title of the application.
> version: Provides the version of the application API.
> description: A short description of the application.
> contact: The contact information for the exposed API.

By taking the following statement that can be found in the [Introduction](https://www.asyncapi.com/docs/reference/specification/v2.6.0#introduction):

> The AsyncAPI Specification defines a set of files required to describe the API of an [application](https://www.asyncapi.com/docs/reference/specification/v3.0.0-next-major-spec.12#definitionsApplication).

I vote for unifying these under one term to avoid any possible confusion. I believe we should stick with the `Application API` term.

cc @derberg @jonaslagoni @alequetzalli @dalelane @fmvilas

**Comment by timmiedinnie** [comment]
As stated in my PR:

I agree there should be a change in favor of consistency.

However the suggestion to replace "Application" with "Application API" may not be suitable in most contexts. The resulting phrase, "The Application's Application programming interface," could be confusing or redundant.

In this proposed change, only a few instances of "Application" were replaced with "Application API," and it may not be appropriate in all situations. Furthermore, replacing "API" with "Application API" often creates even more awkward phrasing.

Therefore, I have submitted https://github.com/asyncapi/spec/pull/950 for review purposes only. In my opinion, using the term "API" consistently would be a better approach.

**Comment by smoya** [comment]
To the rest of codeowners @fmvilas @derberg @dalelane @char0n:  do you think this makes sense?

**Comment by sagnik3788** [comment]
hello @smoya  can you assign me any issue so that i can work on docs

**Comment by smoya** [comment]
> Therefore, I have submitted #950 for review purposes only. In my opinion, using the term "API" consistently would be a better approach.

Sorry for not coming back to this earlier, but I noticed I never shared I also agree, after reviewing your PR, that the simple term "API" could fit better.

Would you be happy to work on that and close https://github.com/asyncapi/spec/pull/950 @timmiedinnie ?

**Comment by smoya** [comment]
With your 👍 reaction, I understand you @timmiedinnie are gonna work on the suggested change. 
I closed https://github.com/asyncapi/spec/pull/950 in favour of that new PR you will create.

Thank you so much! 🙌

**Comment by helios2003** [comment]
Is this issue still relevant?

**Comment by smoya** [comment]
> Is this issue still relevant?

I believe it is. But consider the discussion that happened in this issue and how it does not make sense to just replace all terms in favour of "API". There are cases that make sense, others not. That's the real work this issue is about, to find when it does make sense.

**Comment by helios2003** [comment]
Yes, in my PR I tried to take care of it. Can you please review it? @smoya

**Comment by xopino** [comment]
Hello everyone! 👋

I’m new to the discussion and have been following along with interest. I’ve also been a bit confused by the term "application" 🤔. It seems to be used in different ways—sometimes referring to a schema in the spec (See: [definitionsApplication](https://www.asyncapi.com/docs/reference/specification/v3.0.0#definitionsApplication)), and other times to the spec itself as an application (See [introduction](https://www.asyncapi.com/docs/reference/specification/v3.0.0#introduction)).

For those of us working on multiple applications using this spec, it would be super helpful to have consistency in this term.

The term "Application API" makes sense to me as it clearly refers to "the API of an application," avoiding the potential confusion that "API" alone could cause—where it might be interpreted as a single API serving multiple applications.

I hope this helps 😊

**Comment by Anam-shaikh2003** [comment]
hello everyone!
There is some application link issues its page does not working well.
I think there is need to change the code on application link.
![issues page](https://github.com/user-attachments/assets/f504d946-0b8a-439a-956e-afd3bcaffc3e)

**Comment by Raghavjha60570** [comment]
Does this issue still open?

**Comment by smoya** [comment]
> Does this issue still open?

I believe time gave the answer and it doesn't seem it has any meaning anymore.

Feel free to reopen it if applies.
