### ISSUE TITLE
Docs Tutorial with Killercoda Errors

### ISSUE THREAD

**Issue by thaxy** [asyncapi/spec#959]
### Describe the bug
Visit the https://killercoda.com/asyncapi/scenario/streetlight-tut tutorial. The link can be found in the official docs [here](https://www.asyncapi.com/docs/tutorials/streetlights-interactive). Installation of ``ag`` or ``@asyncapi/cli`` doesn't work.

### To Reproduce
1. Visit killercoda tutorial
2. Execute ``npm install -g @asyncapi/generator``. Then run ``ag`` or ``ag asyncapi.yaml @asyncapi/nodejs-template -o output -p server=mosquitto`` => errors
3. Execute ``npm install -g @asyncapi/cli`` => errors
### Expected behavior
The tutorial should work as suggested.

### Additional context
It seems that ``ag`` is deprecated.  [See here](https://github.com/asyncapi/generator/issues/1008). I thought I would continue with the CLI but no luck with that either.

**Comment by derberg** [comment]
@thaxy thanks a lot for opening the issue, tutorial https://killercoda.com/asyncapi/scenario/streetlight-tut is now fixed. There was issue with nodejs installation in the environment, and that is why packages did not work. `ag` is deprecated but should work, anyway I updated tutorial to use AsyncAPI CLI instead as this is they way to go long term.

Thanks again!

**Comment by derberg** [comment]
@thaxy I click it through by myself, but if you think there still is some issue, just leave a comment and I just reopen
