### ISSUE TITLE
Add logo of new silver sponsor and remove old platinum

### ISSUE THREAD

**Issue by derberg** [asyncapi/spec#966]
readme changes:
- new silver is https://www.svix.com/ - brand logo -> https://www.svix.com/press/
- for bronze sponsor `Ably` use a logo with name of company, like for others -> https://ably.com/press-center/ably-branding
- remove IQVIA as platinum

context why IQVIA should be removed:
![Screenshot 2023-08-29 at 17 24 07](https://github.com/asyncapi/spec/assets/6995927/c1f78d8e-a597-4ba8-bbd1-9a998a99f192)

**Comment by DarrenDsouza7273** [comment]
Got it @derberg will do it

**Comment by DarrenDsouza7273** [comment]
Hi @derberg sorry for taking this up so late
but there are 4 logos of the bronze sponsor Ably which one should i use

**Comment by derberg** [comment]
@DarrenDsouza7273 please us the one that looks the same like the one you already used, but with text next to it, on the right
