### ISSUE TITLE
dotnet message validation

### ISSUE THREAD

**Issue by hfroliveira** [asyncapi/spec#973]
Hello,

I Would like to know if there is a way to validate incoming messages against an asyncapi using csharp.  I think that with the available dotnet tools it not possible to achieve something like WaleedAshraf/asyncapi-validator for dotnet. I'm I wrong?

Thanks.

**Comment by derberg** [comment]
Hey, list of all the tools is in https://www.asyncapi.com/tools

If the tool is not on the list, most probably do not exist. Then you can start discussion in https://github.com/orgs/asyncapi/discussions/categories/ideas

Closing as question is not related to spec
