### ISSUE TITLE
Provide definition for the reply

### ISSUE THREAD

**Issue by Tenischev** [asyncapi/spec#980]
In current Spec v3 pre-release the `reply` appear first time as `operationObject` field:
https://github.com/asyncapi/spec/blob/abfae495b0fbb88fccd56f8099e466a83f4b76ab/spec/asyncapi.md?plain=1#L843
with the description `The definition of the reply in a request-reply operation`.
But Spec v3 has no definition or describing what is meant under `request-reply operation`.
@jonaslagoni wrote the [blog post](https://eventstack.tech/posts/asyncapi-v3-request-reply) describing what it could be, but the blog post is not the Specification. Blog post could be a spice for a cake, but not the cake.

I suggest to provide definition of `reply` in the [Definitions](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#definitions) section, maybe as subpart of Message definition.

**Comment by smoya** [comment]
> I suggest to provide definition of `reply` in the [Definitions](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#definitions) section, maybe as subpart of Message definition.

Wondering if it is not already covered by the description of what an [Operation Reply Object](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#user-content-operation-reply-object) means.

> Describes the reply part that MAY be applied to an Operation Object. If an operation implements the request/reply pattern, the reply object represents the response message.

**Comment by Tenischev** [comment]
For me description of [Operation Reply Object](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#user-content-operation-reply-object) and definition of [Message](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#definitionsMessage) are a bit not match.

Message:
> Since a message is a generic mechanism, it can support multiple interaction patterns such as **event, command, request, or response.**

Reply Object:
>  If an operation implements the **request/reply pattern**, the **reply** object **represents the response** message.

I feel here a gap, like "what exactly is `request`?", consequently "is it `send` or `receive` operation?". (_For me now it's clear, but I feel some degree of uncertain, when read Spec first time_)

If we have a look of [EIP request-reply definition](https://www.enterpriseintegrationpatterns.com/patterns/messaging/RequestReply.html), I would say it a bit more solid

> Send a pair of Request-Reply messages, each on its own channel.
> 
> Request-Reply has two participants:
> 
> Requestor – **Sends** a **request** message and waits for a **reply** message.
> Replier – **Receives** the **request** message and responds with a **reply** message.

**Comment by derberg** [comment]
Defenitely like the idea of adding another definition, as this is what `Definitions` are for in the spec, to introduce the concept

@Tenischev do you have a suggestion for a good paragraph?

**Comment by Tenischev** [comment]
@derberg to be consistent I also provide changes in other part of document related with reply or "response" message.

### <a name="definitionsMessage"></a>Message
A message is the mechanism by which information is exchanged via a channel between [servers](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#definitionsServer) and applications. A message MUST contain a payload and MAY also contain headers. The headers MAY be subdivided into [protocol](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#definitionsProtocol)-defined headers and header properties defined by the application which can act as supporting metadata. The payload contains the data, defined by the application, which MUST be serialized into a format (JSON, XML, Avro, binary, etc.). Since a message is a generic mechanism, it can support multiple interaction patterns such as event, command, request, or reply.
#### <a name="definitionsReplyMessage"></a>Reply message
A reply is a special type of message used in the request-reply interaction pattern and can only be used in combination with a request message. In the request-reply interaction pattern, messages are defined as follows: [Sender](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#sender) sends a request message and waits for a reply message, while [Receiver](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#receiver) receives the request message and responds with a reply message.

----

#### <a name="operationObject"></a>Operation Object
Describes a specific operation.
##### Fixed Fields
Field Name | Type | Description
---|:---:|---
<a name="operationObjectReply"></a>reply | [Operation Reply Object](#operationReplyObject) &#124; [Reference Object](#referenceObject)  | The definition of the reply part in a request-reply interaction.  When this property is defined, the [messages](operationObjectMessages) represent request messages in a request-reply interaction.

----

#### <a name="operationReplyObject"></a>Operation Reply Object
Describes the reply part that MAY be applied to an Operation Object. If an operation implements the request-reply interaction pattern, this object represents the reply address/channel and the reply message.

----

#### <a name="messageBindingsObject"></a>Message Bindings Object
Map describing protocol-specific definitions for a message.
##### Fixed Fields
Field Name | Type | Description
---|:---:|---
<a name="messageBindingsObjectHTTP"></a>`http` | [HTTP Message Binding](https://github.com/asyncapi/bindings/blob/master/http/README.md#message) | Protocol-specific information for an HTTP message, i.e., a request or a reply.

**Comment by derberg** [comment]
@Tenischev can you show it in a draft PR 🙏🏼

**Comment by derberg** [comment]
I believe it is still needed
