### ISSUE TITLE
Fix some V3 examples

### ISSUE THREAD

**Issue by Amzani** [asyncapi/spec#985]
-  https://github.com/asyncapi/spec/blob/next-major-spec/examples/gitter-streaming-asyncapi.yml#L39 (`type` is removed in HTTP binding in V3)
- Validation error in https://github.com/asyncapi/spec/blob/next-major-spec/examples/websocket-gemini-asyncapi.yml

**Comment by derberg** [comment]
> https://github.com/asyncapi/spec/blob/next-major-spec/examples/gitter-streaming-asyncapi.yml#L39 (type is removed in HTTP binding in V3)

yup, you mind opening a PR?

> Validation error in https://github.com/asyncapi/spec/blob/next-major-spec/examples/websocket-gemini-asyncapi.yml

this error was related to errors in JSON Schema fixed with https://github.com/asyncapi/spec-json-schemas/pull/434. Where did you validate this document? in Studio? is studio using latest JSON Schema and Parser?

**Comment by derberg** [comment]
fixed with https://github.com/asyncapi/spec/pull/995
