### ISSUE TITLE
Add definition for Operation to spec 3.0

### ISSUE THREAD

**Issue by buehlefs** [asyncapi/spec#993]
Since version 3 elevates operations to a top level component (and spec v3 Operations have a different semantic compared to 2.x) they should have a dedicated definition in the [definitions](https://github.com/asyncapi/spec/blob/next-major-spec/spec/asyncapi.md#definitions) section. (Additionally, operations could also be added to the [concepts](https://www.asyncapi.com/docs/concepts))

I do not have a fleshed out proposal yet (I may create a PR if I find the time to do so), so feel free to propose a definition or create a PR.

Suggested starting point:

> An operation describes a specific action an application can take to interact with the async api.
> Operations are performed by sending (or receiving) messages to (or from) channels.

Related Issues:
- #980
- #618 Issue about the changes of operations

**Comment by derberg** [comment]
Hey, yes, you're right, we need it. I think your text is ok.

@smoya @fmvilas @char0n @dalelane thoughts?
